### ISSUE TITLE
Show selected skilltree in advancements

### ISSUE THREAD

**Issue by scomans** [MyPetORG/MyPet#1020]

**Comment by Andre601** [comment]
So if I understand this right, MyPet v3 should show the skilltree in the advancements?

With progress to show how much the Pet needs to get the next level (get to the next advancements)?

**Comment by xXKeyleXx** [comment]
It will be a visual representation of the skilltrees, so players know what to expect when they level up their pet with the skilltree they selected.

**Comment by xXKeyleXx** [comment]
https://www.spigotmc.org/threads/advancementapi-create-1-12-advancements.240462/
