### ISSUE TITLE
Pet feed itself from inventory.

### ISSUE THREAD

**Issue by WolfGangS** [MyPetORG/MyPet#1077]
It'd be nice if the pet would eat out of its inventory.

So if it has a food type it accepts in the inventory just -1 to that stack and feed itself.

**Comment by WolfGangS** [comment]
I just noticed that there was actually an issue that mentioned this, but it wasn't in the title.

**Comment by xXKeyleXx** [comment]
Which one was it? Didn't even know there was one there already.

**Comment by WolfGangS** [comment]
Issue #783

It had a few in a list. 

I looked into doing it myself but it would need extending to the custom inventory system you have. But the structure of it looks beyond me.
