### ISSUE TITLE
Skript support

### ISSUE THREAD

**Issue by scomans** [MyPetORG/MyPet#1124]
Has anyone any experience with Skript?

https://github.com/SkriptLang/Skript

**Comment by zerafox** [comment]
I"m not familiar at all what Skript does or is capable of, but what kind of support can one have for Skript in the first place?
Pet's running Skript based abilities or something?

**Comment by xXKeyleXx** [comment]
Maybe in the long run but I think it would allow server owners to access/modify pets without knowing to write plugins in Java. For example give them XP or change their appearance and everything else you can do with the MyPet API.
