### ISSUE TITLE
Horses desync with client while riding

### ISSUE THREAD

**Issue by Tiplish** [MyPetORG/MyPet#1181]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2
**MyPet Build/Version:**
MyPet-3.0-SNAPSHOT.jar #1282
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
Pet is at the same location than the player when the player ride the pet
**What happens instead of that?**
When the player dismount, sometimes the pet is stuck far before the position of the player when he dismounts. 

For example, on client side, you think that you are on the pet in a certain location, but if everyone else see you, you are stuck against a cobblewall, a tree or something else. I've try, it happends very often when you haven't a lot of space around you (in a forest or a small street).
**Error:**
No error in console.

**Comment by xXKeyleXx** [comment]
Do you use any anti cheat plugins?

**Comment by Tiplish** [comment]
No, only natives options from bukkit or spigot. At your side, there is no problems like this? :s

**Comment by xXKeyleXx** [comment]
It works fine on my small test server but I never tested it for a longer period of time as I don't have my own public MC server 🤷‍♂️ 
But I will test it and try to figure it out

**Comment by Tiplish** [comment]
Ok if you would a production testing environment, you could come to try it at our server. This "bug" is easy to reproduce for us

**Comment by xXKeyleXx** [comment]
I think I will figure it out by myself but could you do a quick test and check if it happens with horses too?

**Comment by Tiplish** [comment]
i've try it with Horse, Donkey and Mule as i remember. I could try again. 

I've found that, if there is some low TPS on the server, the stuck mount occure more often. I don't know if it could help you.

**Comment by xXKeyleXx** [comment]
> an anticheat

A plugin name would be great 🤔

**Comment by Tiplish** [comment]
Any news about this problem? :s

**Comment by xXKeyleXx** [comment]
Oh I'm sorry I did not reply yet. I tried it further on my local testserver and I never got it to reproduce your problem. If you tell me your server IP I would like to see it in action 🤔

**Comment by Tiplish** [comment]
nefald.fr

**Comment by xXKeyleXx** [comment]
I tried to fix it the last 5 hours and I have no idea how I could possibly do it :( Everything I tried made it even worse. 

It happens because the horse riding is 100% clientside and somehow the speed on the server doesn't match the speed on the client.

😭

**Comment by xXKeyleXx** [comment]
I might be able to do something with ProtocolLib but I can't promise anything

**Comment by Tiplish** [comment]
Ok i'm waiting for feedback o/

**Comment by Tiplish** [comment]
Hi, 

Any news about this problem? 

Thanks o/

**Comment by xXKeyleXx** [comment]
Unfortunately not 😢

**Comment by Tiplish** [comment]
This problem occure only with horses/donkey/mule that's right? Or it could happend too with spider/polar_bear etc...?

**Comment by xXKeyleXx** [comment]
No it just happens with horses/donkey/mule as these mobs have a clientside riding logic. For all other mobs the logic is just serverside and no problem.

**Comment by Tiplish** [comment]
It's weird :s Do you have some clue to solve this? I have to know if i might try another kind of mount or if i could just wait that you find a solution. Horse/donkey/mule are more logic as mount but it doesn't work, i prefer to try another way :p

**Comment by Saelman** [comment]
Hey, Replying to this thread cause im having the same issue, using spigot version 1.14.3.

**Comment by PiruSax** [comment]
Hi, i'm having this same Issue when I try to FLY with this mountable pets (Horse,SkeletonHorse,ZombieHorse,Mule,Donkey). I hope u can fix this soon

**Comment by VeInArDiS** [comment]
Recently on my server too there was such problem at the friend.
He says he's gone, but he's standing still (for me). Sometimes he even teleports to a point that has long passed (in the descent from horse).

**Comment by zerafox** [comment]
Just gonna throw this link in here then:
[Discord Report](https://discordapp.com/channels/145501914795212800/523564523760779290/702726437400084530)

**Comment by LeanCraft511** [comment]
There is already any solution to this issue? I have the same problem and i need to solve it.

**Comment by zerafox** [comment]
No, there is no solution to this yet.
This is why the ticket is still open.
Keyle is doing his best to find a solution.

If this is too much of a problem for you, simply remove the Ride option from the afflicted pets until it's fixed.
Until then, please be patient.

**Comment by MarvinKlar** [comment]
Having the same issue on Paper 1.17.1, Looking for a fix, please keep me updated!

If I can help with this, please share the information you have so far on this problem!

**Comment by Jakllp** [comment]
Fixed since `3.12-SNAPSHOT-B1666`
