### ISSUE TITLE
Add Fire Resitance to nether mobs

### ISSUE THREAD

**Issue by scomans** [MyPetORG/MyPet#1237]
Add Fire Resistance + option to disable it.

**Comment by zerafox** [comment]
I'd like to request that this sort of feature be added as option within skill trees or to all pets.
Not just pets that can be found only in the Nether.

**Comment by zerafox** [comment]
Same as Ticket #555 
Proceeding to close issue #555 for sake of cleanliness and orderly fashion. ;P
