### ISSUE TITLE
Mypet.command.store not working 1.16.3

### ISSUE THREAD

**Issue by Balorien** [MyPetORG/MyPet#1422]
# Bug report

* [x] I saw a similar bug report however using luckyperms i added all necessary permissions including this one however it does not seem to work

## Describe the bug

The command /petstore does not work, it works when im in god mode but i added the permission to the defualt user along with the rest but this one doenst want to work.

**Comment by Balorien** [comment]
EDIT: I tried to use it with a another permission plugin same results, everything works except for the petstore

> 
op.false
MyPet.command.store
MyPet.leash.Blaze
MyPet.leash.Cat
MyPet.leash.CaveSpider
MyPet.leash.Chicken
MyPet.leash.Cow
MyPet.leash.Creeper
MyPet.leash.Donkey
MyPet.leash.Drowned
MyPet.leash.Enderman
MyPet.leash.Evoker
MyPet.leash.Fox
MyPet.leash.Hoglin
MyPet.leash.Horse
MyPet.leash.Husk
MyPet.leash.IronGolem
MyPet.leash.Llama
MyPet.leash.MagmaCube
MyPet.leash.Mooshroom
MyPet.leash.Mule
MyPet.leash.Ocelot
MyPet.leash.Panda
MyPet.leash.Pig
MyPet.leash.Piglin
MyPet.leash.PigZombie
MyPet.leash.Pillager
MyPet.leash.PolarBear
MyPet.leash.Rabbit
MyPet.leash.Ravager
MyPet.leash.Sheep
MyPet.leash.Skeleton
MyPet.leash.SkeletonHorse
MyPet.leash.Slime
MyPet.leash.Snowman
MyPet.leash.Spider
MyPet.leash.Stray
MyPet.leash.Strider
MyPet.leash.TraderLlama
MyPet.leash.Villager
MyPet.leash.Vindicator
MyPet.leash.WanderingTrader
MyPet.leash.Witch
MyPet.leash.WitherSkeleton
MyPet.leash.Wolf
MyPet.leash.Zombie
MyPet.leash.ZombieHorse
MyPet.leash.ZombieVillager
MyPet.leash.ZombifiedPiglin
MyPet.command.release
MyPet.command.name
MyPet.command.name.color
MyPet.command.switch
MyPet.command.store
MyPet.command.info.other
MyPet.petstorage.limit.30
decoheads.use
decoheads.category.*
decoheads.head.*

> 
This is the content for my permission cache.

**Comment by DARG367** [comment]
Having the same issue. Added every single permission with my MyPet.petstorage.limit.100 and when I type /petstore or try to buy a pet it says "You can not store more than **0** pets."

I'm on 1.16.4
Paper 277

**Comment by mcdaddytalk** [comment]
Same issue as above:

Details:
Using Paper 1.16.5, LuckPerms, MyPet 3.11 build 1588 - I have given permissions to players to use mypet.command.store but when they use /petstore is says they are not allowed to use it
Max petstore is 45 and mypet.petstorage.limit is below that

**Comment by mcdaddytalk** [comment]
Found the issue....   mypet.petstorage.<limit> was the old format
the new format:  mypet.petstorage.limit.<limit>

so with:  mypet.command.store with mypet.petstorage.limit.<limit> (limit must be less than config limit)
I am able to run /petstore
