### ISSUE TITLE
A Custom Event for buying Pets etc.

### ISSUE THREAD

**Issue by Avankziar** [MyPetORG/MyPet#1443]
# Feature request

What part of MyPet needs this?
- [x ] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

I would like to see a custom event that is called when something is purchased for example. Be it pets or for example resurrections of pets.

## Describe the solution you'd like

The events should best be built so that it is recognizable what you have paid for. Means, for example, which pet or any action which is displayed by string/enum.

## Describe alternatives you've considered

I have already looked into the other options, however, I think they are inefficient. (For example, intercept the commands, or just query Vault.) The point is that I want to know what you pay for, not just the amount of money.

**Bukkit/Spigot/Bungee Build/Version:**
All Versions.

**Comment by Jakllp** [comment]
[MyPetCreateEvent](https://github.com/MyPetORG/MyPet/blob/master/modules/API/src/main/java/de/Keyle/MyPet/api/event/MyPetCreateEvent.java) accomplishes this

See Sources -> PetShop
