### ISSUE TITLE
I am running mypet  3.10 on Minecraft 1.16.1, the plugin loads but when I run /mypet I get a console error,

### ISSUE THREAD

**Issue by cantercrow** [MyPetORG/MyPet#1448]
Hi, I am running mypet  3.10 on Minecraft 1.16.1, the plugin loads but when I run /mypet I get a console error,

https://pastebin.com/24js5Wfg

Thanks

**Comment by Jakllp** [comment]
3.10 was not compatible with that version - newer versions (aka 3.12-SNAPSHOT) should work
