### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by javitomo1** [MyPetORG/MyPet#1471]
Hello,
When I restart the server and log in for the first time, I get that WARN in console, but only the first time I log in
Greetings
server is running Paper version git-Paper-691 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
https://pastebin.com/zR0z6xPe

**Comment by itdevsteve** [comment]
Getting a similar error message as well.  Adding in my error log to add additional info.

git-Paper-739 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
openjdk 11.0.11 2021-04-20

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by de.Keyle.MyPet.api.util.ReflectionUtil (file:/srv/minecraft/plugins/MyPet-3.11-SNAPSHOT-B1639.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of de.Keyle.MyPet.api.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Jakllp** [comment]
Should be fixed in newer versions of MyPet
