### ISSUE TITLE
problems with spawn

### ISSUE THREAD

**Issue by emmet033** [MyPetORG/MyPet#1489]
# Bug report

* [x ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

the pets doesnt spawn in any world, region or flag: all the worlds are in the default group at the "worldgroups.yml" document BUT when i used "/petadmin create" it works until i disconnect or i leave the world
## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. install plugin as the guide says
2.buy the pet in a NPC
3. it takes the money and give me the pet
4. when i use /petswitch or /petc it says that the pets cant spawn in this world
5. we try in all the worlds and we check 1000 times the flags, event in the new worlds without any flags works

...

## Expected behavior

_A clear and concise description of what you expected to happen._

well i expected that the pet appears, i think it will be just a bug of the dev version 

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/90502217/133481984-ae95a4e4-1d53-4e9d-af27-560573a1825e.png)

its write in spanish but it says that pets are now allowed in the world(they are allowed in the flags so idk why it doesnt work)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
https://mega.nz/file/pkAiGRRS#O8_TLzloKgEDS7-DgHDK22gy-6nNSlOo4DK74JApVxw
**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**
 MyPet-3.12-SNAPSHOT-B1643.jar 
**What is the expected result?**
Use the pets with normatilly
**What happens instead of that?**
it just give us the message "pets are not allowed in th world"
**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
Does this error still persist even with newer versions?
