### ISSUE TITLE
Hello! I made a blowfish as a pet, but I do not specify the option "baby", however it is small, it should be inflated like a blowfish from a spawn egg. I tried to make option "adult" but it is still small

### ISSUE THREAD

**Issue by Pikachu2p** [MyPetORG/MyPet#1492]
Hello! I made a blowfish as a pet, but I do not specify the option "baby", however it is small, it should be inflated like a blowfish from a spawn egg. I tried to make option "adult" but it is still small

**Comment by Jakllp** [comment]
What version (So Minecraft and Build Number of the plugin) were you using?

**Comment by Jakllp** [comment]
You gotta select the puff-value

You're talking about option so I'm guessing you're defining a petshop.
I would suggest you try the `/petadmin create` command first as that will Tab-Complete you the options you have.

For a Pufferfish you have the option of "puff" which can be set to none, semi and fully.
So basically:
`/petadmin create Pikachu2p Pufferfish puff:fully` should give you a pufferfish that is fully puffed - As for the petshop-options: There you would put puff:fully
