### ISSUE TITLE
Enderdoragon does not eat

### ISSUE THREAD

**Issue by KazunariShimizu** [MyPetORG/MyPet#1494]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Enderdoragon does not eat
2. can not ride
...

## Expected behavior

_A clear and concise description of what you expected to happen._

ProtocolLib 4.7.0

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-268 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9087993)

**MyPet Build/Version:**
version 3.0-SNAPSHOT-b742P

**What is the expected result?*
eat & ride

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
no ERROR code

**Comment by Jakllp** [comment]
Due to some changes made for 1.17 it is currently not possible to interact with the enderdragon pet in any way without spamming your console

This issue is known and I can‘t say if and when it can be fixed

**Comment by Jakllp** [comment]
Fixed in `MyPet-3.12-SNAPSHOT-B1670`
