### ISSUE TITLE
[BUG] pet death message

### ISSUE THREAD

**Issue by kedavlar** [MyPetORG/MyPet#1497]
## Describe the bug

When a pet is killed by a player, the kill message appears in chat even if the death messages are disabled on the server

## To Reproduce

Just kill a pet and read the chat

## Expected behavior

Death message dosent appear

## Actual behaviour
![error](https://user-images.githubusercontent.com/85011614/138739588-15b9271c-9088-48b1-9303-af3005316f74.PNG)

**Bukkit/Spigot/Bungee Build/Version:**

1.16.5 tuinity

**MyPet Build/Version:**

Dev 1649

**Comment by Jakllp** [comment]
So I've looked into the code for the death messages and found the following:
The plugin checks if there is a default death cause (so one that minecraft knows). If there is it will send that cause to the player just like Minecraft would do, and lets Minecraft handle the translation.
The MyPet-Message will only be used if there is a different cause.

I might add an option to only use the mypet death message at some point but right now I don't think it's necessary.

With that said I will comment on here again once the new build that includes the gamerule-awareness for deathmessages is out (should be ready next week - wanna finish some other stuff)

**Comment by kedavlar** [comment]
thanks a lot!
