### ISSUE TITLE
Hi! I'm not exactly sure that this function is not there. Is it possible to make a snow fox in the mob type of an ordinary fox? That is, write in the type: snow. I did so, but it doesn't work. How can I make a snow fox?

### ISSUE THREAD

**Issue by Pikachu2p** [MyPetORG/MyPet#1499]
Hi! I'm not exactly sure that this function is not there. Is it possible to make a snow fox in the mob type of an ordinary fox? That is, write in the type: snow. I did so, but it doesn't work. How can I make a snow fox?

**Comment by CJBlakey** [comment]
Should be type:white I think

**Comment by Jakllp** [comment]
Yeah it is type:white

**Comment by Pikachu2p** [comment]
I tried to insert it into PetType, but the name of the mob itself is needed there. If I insert Fox:white, but it doesn't work. There are still Options, I tried inserting there, but I still don't have a snow fox.

Below I have attached how I did it, but no setup works.

      Fox:
        Name: Foxy
        PetType: Fox:white
        EXP: 0
        Price: 100

      Fox:
        Name: Foxy
        PetType: Fox
        EXP: 0
        Price: 100
        Options:
          - white

      Fox:
        Name: Foxy
        PetType: Fox
        EXP: 0
        Price: 100
        Options:
          - snow

**Comment by Jakllp** [comment]
```
  Fox:
    Name: Foxy
    PetType: Fox
    EXP: 0
    Price: 100
    Options:
      - type:white
 ```

**Comment by CJBlakey** [comment]
Would it be worth looking into a tab complete that checks the type enum and provides options?

**Comment by Jakllp** [comment]
It actually exists
Try `/petadmin create YouName fox ` and it will suggest type:red and type:white
The problem here was the Options: syntax in the pet-shops.yml file

**Comment by CJBlakey** [comment]
Awesome, does the same option exist for pets that use the integer variant? Such as parrots/axolotls? I don’t recall seeing the tab complete options in the past

**Comment by Jakllp** [comment]
Nope, not for those as it's not really descriptive I guess

**Comment by Pikachu2p** [comment]
Yes, I tried to enter it and everything worked, I also changed the option with the axolotl and it also works.  I got a brown axolotl. Thank you :)


  Fox:
    Name: Foxy
    PetType: Fox
    EXP: 0
    Price: 100
    Options:
      - type:white


      axolotl:
        Name: Axolotl
        PetType: Axolotl
        EXP: 0
        Price: 100
        Options:
          - variant:1
