### ISSUE TITLE
[Bug] Ocelot not staying put

### ISSUE THREAD

**Issue by Pikachu2p** [MyPetORG/MyPet#1500]
Hi!  I have a problem. I can plant all the mobs and they will sit, but I can't plant an ocelot in any way. I press "shift" and the left mouse button, but he does not sit down like other pets.

**Comment by Jakllp** [comment]
Does the ocelot still follow you or is it just the sitting position?

**Comment by Pikachu2p** [comment]
He still follows me, but he should be sitting and the barrier icon should be lit in front of him

**Comment by Jakllp** [comment]
That's interesting. You are using 1.17?

Ocelots have lost the ability to "sit" in 1.14 I think but they should still remain in one place. Will check

**Comment by Jakllp** [comment]
Checked, will be fixed with next build

**Comment by Pikachu2p** [comment]
Thank you)

**Comment by Pikachu2p** [comment]
> Это интересно. Вы используете 1.17?
> 
> Я думаю, оцелоты потеряли способность «сидеть» в 1.14, но они все равно должны оставаться на одном месте. Проверю

Yes, I use 1.17
