### ISSUE TITLE
Hi! Help please. I want to make it so that by clicking on my pet with the compass, which is the server menu from the ItemJoin plugin, I can sit on my pet. My riding skill is turned on and I checked it with a regular compass, everything works, but when I click the compass from the itemjoin plugin, then this player does not sit on the pet and cannot ride. I tried to write the name of the menu compass itself, but it didn't work, in Itemjoin I tried to create a regular compass without signatures and it still doesn't work, I wrote to the itemjoin developer, but there is no answer yet. I hope you can help me

### ISSUE THREAD

**Issue by Pikachu2p** [MyPetORG/MyPet#1502]
Hi! Help please. I want to make it so that by clicking on my pet with the compass, which is the server menu from the ItemJoin plugin, I can sit on my pet. My riding skill is turned on and I checked it with a regular compass, everything works, but when I click the compass from the itemjoin plugin, then this player does not sit on the pet and cannot ride. I tried to write the name of the menu compass itself, but it didn't work, in Itemjoin I tried to create a regular compass without signatures and it still doesn't work, I wrote to the itemjoin developer, but there is no answer yet. I hope you can help me

**Comment by scomans** [comment]
Fill out the template and don't use the text as the title

**Comment by Pikachu2p** [comment]
I didn't understand a bit. What did you mean?
