### ISSUE TITLE
Strange SQlite error

### ISSUE THREAD

**Issue by kedavlar** [MyPetORG/MyPet#1504]
## Describe the bug

Sometimes after restart all people pet disappear and when i try to take another pet i have this error of SQlite https://pastebin.com/Ff7uNGg6

## To Reproduce

1.  Restart
2.  Take pet with command /petadmin create ..
...

**Bukkit/Spigot/Bungee Build/Version:**

1.16.5 tuinity

**MyPet Build/Version:**

3.12 DEV 1649

**Comment by Jakllp** [comment]
This might be a Tuinity-Issue, can't say yet

**Comment by kedavlar** [comment]
let me know if you have some news about this
