### ISSUE TITLE
1.18 update

### ISSUE THREAD

**Issue by celophys** [MyPetORG/MyPet#1508]
# Feature request

The plugin is not compatible with 1.18, using the last version, it shows an error in chat, will it be updated?

**Comment by scomans** [comment]
https://github.com/Jakllp/MyPet/releases/tag/v1.18-dev1

**Comment by celophys** [comment]
Ok thanks, the discord link on the page is not valid, where can i find it?

**Comment by scomans** [comment]
The discord link on the spigot page works.
