### ISSUE TITLE
Setting to disable the automatic recall of despawned pets

### ISSUE THREAD

**Issue by MarvinKlar** [MyPetORG/MyPet#1509]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

I want to be able to configure if pets should automatically be recalled, after despawning, when moving to far away from a pet, which I told to stay. The problem is, that I told the pet to stay, but when I move far away, it doesn't stay.

## Describe the solution you'd like

I would like to have a config option like `MyPet.Recall-Pet-After-Despawn` which defaults to `true` (like it is now), which I can set to `false` which will despawn the pet, but not automatically recall it.

## Describe alternatives you've considered

I considered forking the project or canceling the event myself, but I would like to have further support and updates of the plugin. I would like to implement this feature myself, oif there was a guide, helping me setting up the project and beeing able to test changes.

PS: If you could tell me how to build the project on my own, I would love to create a pull request for this.

**Comment by Jakllp** [comment]
First of all: Interesting idea, could probably be added - won't be a priority (at least for me) for now tho.

If you want to do this yourself:
To build MyPet you'll need a few things: 
- A JDK (at least 16, 17 once I merge the 1.18 module) and an IDE (I mean - It's Java)
- Maven
- You'll need to configure a personal access token for github-packages (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token)

If all of that is ready:
- Clone the repo
- Run the install_dependencies script (.sh if you're over on linux, .ps1 if you're over on windows)
- Run `mvn install` (through your IDE or just in a Terminal)

And you should be good to go!

(Also: Feel free to join the MyPet-Discord - I'll probably notice that earlier than issues/comments ^^)

**Comment by MarvinKlar** [comment]
@Jakllp https://github.com/MyPetORG/MyPet/pull/1510
