### ISSUE TITLE
Unmounting pet teleport you to coord you mounted at

### ISSUE THREAD

**Issue by Felina-Lain** [MyPetORG/MyPet#1516]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.
There is an issue that seemed similar, but not quite the same?

## Describe the bug
When riding a pet, dismounting will send you back to the location you mounted the pet.

## To Reproduce
1. Tame a pet, give it the riding tree skill, mount the pet.
2. Ride some distance, the distance doesn't seem to matter, the bug occur no matter how far or close you go.
3. Dismount.
4. Player is teleported back to the coordinate where he mounted. Pet stays at the spot ridden to, until Player move. Then Pet get respawned back next to the player.

## Expected behavior
For the player to stay where he dismount the pet

## Actual behaviour
The player get teleported back to where he first mounted the pet

## Additional context
This happen only for horses(and other horse-like, donkeys etc) as far as I can tell, this happen regardless of saddle being on the pet, this happen regardless of sprinting
I have no anti-cheat on my server, it's a very small server for me and some friends, the only other plugin we have is ShulkerPacks-1.6.3 (a plugin to open shulker in hand)
I did a small video to show the problem:
https://youtu.be/VHcJZCKIl3E

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
https://www.mediafire.com/file/8cqtco8v9v2g2b2/ticket.zip/file

**Bukkit/Spigot/Bungee Build/Version:**
Paper-1.18

**MyPet Build/Version:**
3.12-SNAPSHOT-B1664

**Error:**
```
Server Log at the moment of the error (from the moment I got on the horse, to the moment I dismounted)
https://pastebin.com/bYgmcx8W

**Comment by Jakllp** [comment]
This was fixed with Build B1666 ^^

**Comment by Jakllp** [comment]
Okay I also just realized that this was on 1.18 - I really recommend updating to 1.18.1 bc of: Security and plugin compatibility as MyPet isn't expected to run on 1.18 but 1.18.1 (you can actually join 1.18.1 servers with 1.18)

**Comment by Felina-Lain** [comment]
Updated everything as advised, and indeed, it now works perfectly! thank you very much! :)

**Comment by Jakllp** [comment]
Glad everyting is working now ^^
