### ISSUE TITLE
kill wildstacker stacked mob give no exp to pet

### ISSUE THREAD

**Issue by hkkongou** [MyPetORG/MyPet#1518]
# Bug report

* [ ✅] I have checked other issues to make sure this is not a duplicate.

## Describe the bug
i have upgrade from
MyPet-3.11-SNAPSHOT-B1642
to
MyPet-3.12-SNAPSHOT-B1669
to make my server to compatible for 1.17
after i upgrade the mypet jar, i found out that, killing wildstacker mob does not give exp to mob.

back in B1642, stacked mobs got killed will give exp to pets equivalent to killing 1 mob. 
But in B1669, no exp is given to mobs at any time. 

I also checked that, vanilla mobs does not have problem, exp still given to pets when killed.

This problem should be a mypet problem because the only plugin i changed is mypet, wildstacker haven't been upgrading for anytime and the jar i use is compatible with any minecraft version.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. spawn wildstacker stacked mob
2. kill the mob
3. check pet exp
...

## Expected behavior

_A clear and concise description of what you expected to happen._

exp will be given to pets when stacked mobs are killed, similar to 1 mob is killed

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

no exp is given 

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/7834968/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:** paper-1.17.1-407

**MyPet Build/Version:** MyPet-3.12-SNAPSHOT-B1669

**What is the expected result?** exp given to mob

**What happens instead of that?** 

idk : (

**Error:**
```
no error 
```

**Comment by Jakllp** [comment]
Which version of WildStacker are you using?

**Comment by hkkongou** [comment]
> Which version of WildStacker are you using?

WildStacker-3.6.2-b261

**Comment by Jakllp** [comment]
I've reproduced the bug and will check where it fails and if it is something we can fix on our side

**Comment by Jakllp** [comment]
Fixed with `3.12-SNAPSHOT-B1674`
By https://github.com/MyPetORG/MyPet/commit/db76c3e4f462e0cf4b33c1eae01174dfb907128a
