### ISSUE TITLE
hey when i use a mypet command then it says an internal error occured while attemping to perfom command

### ISSUE THREAD

**Issue by TechnoKraken** [MyPetORG/MyPet#1522]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.
* [ ] i have

## Describe the bug
when i use a mypet command then it says an internal error occured while attemping to perfom command

_A clear and concise description of what the bug is._
i cant use the commands because it makes a error

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior
that it wouldnt make this error

_A clear and concise description of what you expected to happen._
it would let me use the commands whiteout making a error

## Actual behaviour
makes a error

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot/Bukkit

**MyPet Build/Version:**
newest

**What is the expected result?**
that it wouldnt make a error

**What happens instead of that?**
made a error

**Error:**
```
an internal error occured while attemping to perfom command
```

**Comment by TechnoKraken** [comment]
i found out why i didnt see it wasnt supported for 1.17.1

**Comment by Jakllp** [comment]
3.12-SNAPSHOT supports 1.17.1
You can download it via https://mypet-plugin.de/download
