### ISSUE TITLE
/pb aggressive Pets can damage players in Residence

### ISSUE THREAD

**Issue by handy-git** [MyPetORG/MyPet#1524]
/pb aggressive
Pets can damage players in Residence

/luckperms group default permission set MyPet.extended.behavior.aggressive false 
Invalid Invalid Invalid

**Comment by Jakllp** [comment]
Can the owner of the pet damage the other players in this area?

**Comment by Jakllp** [comment]
Will be closed if no further info is provided

**Comment by Jakllp** [comment]
I have no clue what "Invalid Invalid Invalid" means but:

If you don't want players to have the option for aggressive behavior you can just remove the option in the skilltree.

If you want to do it via permissions you'll need to make sure that extended permissions are enabled.
See https://wiki.mypet-plugin.de/setup/permissions#extended-mypet-permissions
