### ISSUE TITLE
Unable to respawn pet with money only

### ISSUE THREAD

**Issue by Shpries** [MyPetORG/MyPet#1525]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
When  Respawn.Time.Disable  in config.yml set to true,died pet will not respawn after the owner pays the respawn cost.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. set  Respawn.Time.Disable  to true
2. kill the pet
3. pay the respawn cost
4. the message shows the cost paid successfully,but the pet is still died

## Expected behavior

_A clear and concise description of what you expected to happen._

The pet respawn after the cost paid
## Actual behaviour
_If applicable, add screenshots to help explain your problem._

the message shows the cost paid successfully,but the pet is still died
here is the config
![image](https://user-images.githubusercontent.com/74460756/155674014-a049704e-ca20-4505-8019-16dbd9de31ae.png)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**purpur 1.18.1-1551

**MyPet Build/Version:**
![image](https://user-images.githubusercontent.com/74460756/155674079-90ea6dbf-194c-4407-b605-fa70ae1919bf.png)

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
no error
```

**Comment by Jakllp** [comment]
Confirmed to be a general bug - will fix soon

**Comment by Jakllp** [comment]
Fixed with `3.12-SNAPSHOT-B1674`
By https://github.com/MyPetORG/MyPet/commit/e1c08a59def12ecaf62c10dfeab49174e66cceff
