### ISSUE TITLE
MyPet doesn't enable on Paper 1.18.2 with Citizens 2.0.29.4 present

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1528]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

MyPet 3.12-SNAPSHOT-B1677 does not enable on Paper when Citizens is present, throwing the following error: https://gist.github.com/mercurialmusic/6ebe72ea235f885ba4ef85d8970520ad

It does enable correctly when Citizens is removed.

**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-234 (MC: 1.18.2)

**MyPet Build/Version:**
MyPet 3.12-SNAPSHOT-B1677 

Also using Citizens 2.0.29 build 4 since I noticed that in the error.

I realize 1.18.2 support may still be a work in progress, but posting in case it's helpful. Thanks for keeping this alive!
If it matters, I've been using B1677 on Paper 1.18.1 (git-Paper-216) with Citizens 2.0.29 build 3 without issue.

Edited to clarify that it enables without Citizens present.

**Comment by Jakllp** [comment]
Please try again with one of the newest dev builds of Citizens [from here] (https://ci.citizensnpcs.co/job/Citizens2/) 
They fixed the issue you're experiencing

**Comment by mercurialmusic** [comment]
Thank you, that seems to have been it!
