### ISSUE TITLE
Citizens

### ISSUE THREAD

**Issue by Gida4** [MyPetORG/MyPet#1529]
# Bug report

Citizens and  Mypet, error under 1.18.2 purpurclip.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
MyPet does not start.

**Bukkit/Spigot/Bungee Build/Version:**
Flamecord 0.8.0
Purpur 1.18.2 build 1584

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1678

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
[mypet_error.txt](https://github.com/MyPetORG/MyPet/files/8220708/mypet_error.txt)

**Comment by Gida4** [comment]
Citizens problem, not Mypet. Sorry.

**Comment by Jakllp** [comment]
Still gonna leave the solution here in case you didn't find one yet:
