### ISSUE TITLE
MythicMobs API Changes Break MyPet's MM Hook

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1530]
# Report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Sorry for the second report in a week about something that's not a bug and not your fault, but MythicMobs has updated their API again, breaking MyPet's MM hook: https://gist.github.com/mercurialmusic/e1a24d689df1a00ef8f9aeb2e554fe5e

Everything still enables properly otherwise, but it might allow for some undesirable pet leashing (at least in our case).

Thanks!

## Additional context

[MythicMobs API Examples](https://github.com/xikage/MythicMobs-API-Examples)
[MythicMobs API Help Channel](https://discord.com/channels/213109157983813633/361529046426976256)

**Bukkit/Spigot/Bungee Build/Version:** git-Paper-240 (MC: 1.18.2)

**MyPet Build/Version:** MyPet-3.12-SNAPSHOT-B1678

**Comment by Jakllp** [comment]
Was brought to my attention over on discord a few hours ago - thanks tho as I like myself some github issues to track everything ^^

Already started working on a fix - might take a bit as we still need to provide legacy-support

**Comment by Jakllp** [comment]
Fixed with `3.12-SNAPSHOT-B1679`
By https://github.com/MyPetORG/MyPet/commit/c9523953edaa9a885f66a0c9a82feafd912b98f1
