### ISSUE TITLE
wildstacker installed, all mob give no XP to pet 

### ISSUE THREAD

**Issue by hkkongou** [MyPetORG/MyPet#1531]
# Bug report

* [✅] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

same problem as #1518  <-- ticket created by me
seems like the problem is not solved afterward

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1.  spawn any vanilla mob(all vanilla mob spawned is handled by wildstacker as wildstacker is loading)
2. kill it
3. check mob xp 
4. unload wildstacker, 
5. spawn any vanilla mob
6. check mob xp

...

## Expected behavior

kill mob have xp

## Actual behaviour

kill mob no xp
video demo:
https://youtu.be/_2lD79qdzUI

## Additional context

[ticket.zip](https://github.com/MyPetORG/MyPet/files/8239167/ticket.zip)
> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
paper-1.18.1-216

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1679

**WS version:**
WildStacker-3.7.0-b297

**What is the expected result?**
have xp

**What happens instead of that?**
no xp

**Error:**
no error

```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
Could you provide your `config.yml`?

**Comment by Jakllp** [comment]
As I suspected:
A configuration error.

1st point: Your config has `PreventLevellingWithout` set to `true` - This refers to skilltrees. The pet in your video has no skilltree and will therefore not gain exp.
2nd point: Your config has `DamageWeightedExperienceDistribution` set to `true`. This means that the pet will only gain the percentage of exp as it dealt damage to the entity -> If the owner kills the entity completely on their own, the pet will not gain any experience.

Set both of these to false and it will work
