### ISSUE TITLE
Mypets with mythicmobs

### ISSUE THREAD

**Issue by Rodas99** [MyPetORG/MyPet#1540]
hi! how can i make a mythicmob my pet? is any way?

**Comment by Rodas99** [comment]
yes i saw it, i put the mythicmob leash-flag on config but every time i tamed my mythicmob it transform into a minecraft mob and not keeping the mythicmob texture and model that it as

**Comment by Jakllp** [comment]
Yes, that is the current expected behavior

**Comment by Rodas99** [comment]
how can i changed that? for not to happen?

**Comment by Rodas99** [comment]
it will ever be possible?

**Comment by Jakllp** [comment]
I cannot say at this point

**Comment by Rodas99** [comment]
it is easily doable?

**Comment by Jakllp** [comment]
I don't know as I haven't looked into it
