### ISSUE TITLE
MyPet repository

### ISSUE THREAD

**Issue by Rocologo** [MyPetORG/MyPet#1541]
# Question about MyPet

Hi Keyle

I cant access you repository anymore? https://repo.keyle.de/ ?

I cant compile MobHunting without access to your repository. 

Kind regards
Rocologo

**Comment by Jakllp** [comment]
You'll probably want to try https://repo.mypet-plugin.de

**Comment by Rocologo** [comment]
I get 403 Access Forbidden

**Comment by Jakllp** [comment]
You won't be able to browse it via a web browser but maven will be able to access it

**Comment by Jakllp** [comment]
Did this work?
