### ISSUE TITLE
Death Loop with HungerSystem.can-kill

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1543]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I'm afraid this is not a well-tested report simply because of the time it would take, but since the implementation of ```HungerSystem.can-kill``` (which we excitedly jumped on), pets have been getting into a starvation death loop since the pets do not seem to regen their hunger or health after respawning. Instead, since hunger is zero, they instantly die again after respawning and before the owner has a chance to feed them.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Starve pet
2. Weep as it death loops
...

## Expected behavior

I'm not sure how the kill system is implemented, but it seems like hunger shouldn't instantly kill the pet on respawn if health is full, to allow owners at least a little bit to feed them again. I think it'd be best to retain the hunger level after death to avoid people cheesing the system, but perhaps something closer to the player behavior where starvation slowly causes damage and you have a window to feed the pet before they die again.

## Actual behaviour

Death loop consists of the normal respawn wait time, respawn, then instant death of the pet as soon as it spawns. I was only able to allow the players to feed their pets by setting ```HungerSystem.can-kill: false``` and reloading.

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** Paper version git-Paper-333 (MC: 1.18.2)

**MyPet Build/Version:** MyPet-3.12-SNAPSHOT-B1686.jar

**Error:**
```
No error.
```

**Comment by Jakllp** [comment]
Damn didn't really think about that... Gonna come up with a solution...

Problem is:
Expected behavior before was that on respawn it would check how hungry a pet is and assign health accordingly (so low saturation -> low health)...
I'll see what I come up with

**Comment by Jakllp** [comment]
Added a new config value "Time-Before-Damage" in `3.12-SNAPSHOT-B1688` with https://github.com/MyPetORG/MyPet/commit/5c8ceeac6a92b4dc74a12dac1520cf555d7148de

**Comment by mercurialmusic** [comment]
Thank you!
