### ISSUE TITLE
Maven Build Fails

### ISSUE THREAD

**Issue by kellsthepenguin** [MyPetORG/MyPet#1545]
# Explain your question

* [x] I have checked existing issue and found none that could answer my question.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._

> I encourage you to try and make an issue with one of the other templates before submitting the general form.

If I try to build mypet-plugin with maven, I'm getting these errors:
Could not find artifact de.keyle:mypet-api:pom:1 in mypet-repo (https://repo.mypet-plugin.de/)
Could not find artifact de.keyle:mypet-skills:pom:1 in mypet-repo (https://repo.mypet-plugin.de/)
Could not find artifact de.keyle:mypet-compat-v1_8_R3:pom:1 in mypet-repo (https://repo.mypet-plugin.de/)
Could not find artifact de.keyle:mypet-compat-v1_9_R2:pom:1 in mypet-repo (https://repo.mypet-plugin.de/)..
Failure to find de.keyle:mypet-gui:pom:1 in https://repo.mypet-plugin.de/ was cached in the local repository, resolution will not be reattempted until the update interval of mypet-repo has elapsed or updates are forced

Is there any way to fix these errors?

**Comment by Jakllp** [comment]
This sounds like you are trying to do `mvn install` out of the `modules/Plugin` directory.

Is that correct?

**Comment by kellsthepenguin** [comment]
> This sounds like you are trying to do `mvn install` out of the `modules/Plugin` directory.
> 
> Is that correct?

yes

**Comment by Jakllp** [comment]
Yes so it does not build all the other modules required.

Just go into the root folder of the repository and do `mvn install` there

**Comment by kellsthepenguin** [comment]
Build failed with error

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:14 min
[INFO] Finished at: 2022-05-24T07:50:01+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mypet-plugin: Could not resolve dependencies for project de.keyle:mypet-plugin:jar:1: Failed to collect dependencies at de.keyle:mypet-api:jar:1: Failed to read artifact descriptor for de.keyle:mypet-api:jar:1: Could not transfer artifact de.keyle:mypet-api:pom:1 from/to github (https://maven.pkg.github.com/MyPetORG/*): Authentication failed for https://maven.pkg.github.com/MyPetORG/*/de/keyle/mypet-api/1/mypet-api-1.pom 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Jakllp** [comment]
And now we're running into github-repository problems.

Parts of MyPet-Artifacts needed to build the plugin are hosted in a repository on github.
Thing with that is that it needs authentication. See this post:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

In short:
You have to generate a github access token in your github profile and put that into a "settings.xml" which needs to be in your local maven directory (aka a directory named `.m2` located in your users home directory)
The linked post explains it fairly well

**Comment by kellsthepenguin** [comment]
The github repository problem was resolved, but I got other error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2022-05-24T08:08:27+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mypet-plugin: Could not resolve dependencies for project de.keyle:mypet-plugin:jar:1: The following artifacts could not be resolved: de.keyle:mypet-api:jar:1, de.keyle:mypet-skills:jar:1, de.keyle:mypet-compat-v1_8_R3:jar:1, de.keyle:mypet-compat-v1_9_R2:jar:1, de.keyle:mypet-compat-v1_12_R1:jar:1, de.keyle:mypet-compat-v1_16_R1:jar:1, de.keyle:mypet-compat-v1_16_R3:jar:1, de.keyle:mypet-compat-v1_17_R1:jar:1, de.keyle:mypet-compat-v1_18_R1:jar:1, de.keyle:mypet-compat-v1_18_R2:jar:1, de.keyle:mypet-gui:jar:1: Could not find artifact de.keyle:mypet-api:jar:1 in central (https://repo1.maven.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Full log: https://pastebin.com/B83JK6qj

**Comment by Jakllp** [comment]
This - again - looks like your building inside the `modules/plugin`-directory.

You want to run `mvn install` in the root directory of the repository (so the directory which contains the `modules`-directory

**Comment by kellsthepenguin** [comment]
Finally Build succeded. Thanks you!
