### ISSUE TITLE
Will it increase warden？

### ISSUE THREAD

**Issue by axin0452** [MyPetORG/MyPet#1548]
# Feature request

What part of MyPet needs this?
- [√] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

Will the 1.19 version increase warden's capture?

**Comment by Jakllp** [comment]
What do you mean with increase warden's capture?

**Comment by axin0452** [comment]
What I mean is to turn the new creatures in 1.19 into mypet
@Jakllp

**Comment by Jakllp** [comment]
Yes. 
Every version since 3.12-SNAPSHOT-B1691 includes all 1.19 mobs

**Comment by axin0452** [comment]
But why can I catch pigs but not frogs and warden
@Jakllp

**Comment by Jakllp** [comment]
Can you try `/pch`?
It should tell you what to do to capture a certain mob.
You might also be running an earlier version of mypet (Build 1690) - Please confirm via `/petadmin build` that you are running a build with a number HIGHER than 1690 (so 1691 to 1693 which is the newest build)

**Comment by axin0452** [comment]
Oh sorry, I seem to have forgotten something, thanks for your kind help
@Jakllp

**Comment by Jakllp** [comment]
No problem ^^
I hope the issue is resolved
