### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by Mosfet947** [MyPetORG/MyPet#1558]
# Bug report

After pet release /petcall don't work

/petb and /petbehavior give nor correct message in /petb is correct after do /petb frendly is not correct 

Please fix i love your plugin

**Comment by Jakllp** [comment]
That isn't a bug but intended behavior.

You have a pet storage and an active pet in an extra, invisible slot. 

`/petswitch` displays your stored pets.
`/petcall` does not access your storage but calls your activated pet.
`/petsendaway` let's your active pet "get a rest" 
`/petstore` sends a pet into storage and clears your active-pet slot

So what does `/petrelease` do? 
It releases your active pet into the world which leaves your active-pet slot empty. 
So now you'll have to select a new pet out of your storage via `/petswitch`
