### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by noobboy0617** [MyPetORG/MyPet#1559]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [x] the website

## Is your feature request related to a problem? Please describe

_A clear and concise description of what you want and what your use case is._

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

## Describe alternatives you've considered

_A clear and concise description of any alternative solutions or features you've considered._

## Additional context

_Add any other context or screenshots about the feature request here._

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Comment by Jakllp** [comment]
Well after you basically haven't filled out anything in the issue itself I'll just be going from the title:
If you're looking for a 1.16.5 compatible version:
Go to https://mypet-plugin.de/download and download the latest dev-build (3.12-SNAPSHOT)
