### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by Akiranya** [MyPetORG/MyPet#1562]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

An SQL error occured each time the server was starting. I'm not sure if it's harmful but seems

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Using MYSQL as data storage method
2. Start the server

## Expected behavior

Should be no errors..

## Actual behaviour

Errors occured each time the server was starting.

## Additional context

[ticket.zip](https://github.com/MyPetORG/MyPet/files/9169498/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:** Current: git-Purpur-1724 (MC: 1.19)*

**MyPet Build/Version:** MyPet-3.12-SNAPSHOT-b#1696

**What is the expected result?**

**What happens instead of that?**

**Error:**
https://pastebin.com/94cZqPky

**Comment by Akiranya** [comment]
Looks like it's unharmful but hopefully it could be fixed cuz it's kinda misleading. I got a pet and restarted the server. The pet was what it was.

**Comment by Jakllp** [comment]
That's a weird one...
It can't find the structure it needs even tho it exists...

**Comment by Jakllp** [comment]
You probably have access to your databases...

I saw that you did not configure a table-prefix so maybe it is clashing with another plugin...  
The plugin checks if the table "info" exists and has content (which it should if mypet is running correctly)

First thing would be to check if that table exists and if not:  
1. Potentially configure a table-prefix (in config.yml)
2. Then let the server run - You'll find that all your pets are gone.

We now need to move the old data into the right place
3. Go into the database, delete the newly created PREFIXpets and PREFIXplayers tables
4. Rename the old pets and players tables to PREFIXpets and PREFIXplayers

Start the server and it should work

**Comment by Akiranya** [comment]
Thanks for the reply!

> I saw that you did not configure a table-prefix so maybe it is clashing with another plugin...
> The plugin checks if the table "info" exists and has content (which it should if mypet is running correctly)

I'm using the 'mypet' database and there are only mypet tables in the database, so there should be no clashing issues..

The structure of the whole DB is like this:

![image](https://user-images.githubusercontent.com/14846342/180633980-14e105a0-6d02-4c1a-95c4-b3a793c65ba9.png)

**Comment by Akiranya** [comment]
Thanks! your solution fixed the issue. And I think I spotted the issue: the "info" table contained no information... that was how this happened. I'm still not sure how the table was empty tho. Anyway, issue fixed. Thank you so much!
