### ISSUE TITLE
[1.12.2] Tamed Problem

### ISSUE THREAD

**Issue by TeQTabanca** [MyPetORG/MyPet#1569]
# Bug report

* [☑️] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

**I tame an ownerless horse and right click on the horse with the leash but nothing happens. It does not give any error in console.**

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. I'm spawning a stray horse,
2. I tame and
3. I right click on the horse with the strap.

## Expected behavior

**You have to right-click on the creature that has been tamed with the horse or tameable creature and tamed with a strap or any other material and it should be mine.**

## Actual behaviour

**I tame the horse and right click on the horse with the strap but nothing happens.**

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version: `git-Spigot-79a30d7-f4830a1 (MC: 1.12.2-SPİGOT)`**

**MyPet Build/Version: `MyPet-3.12-SNAPSHOT-B1700`**

**Error:**
```
No Error in console.
```

**Comment by TeQTabanca** [comment]
### After taming the horse, I was able to own it by right clicking with the strap and hitting the horse once. So, is it possible to have it without hitting it?

**Comment by Jakllp** [comment]
You have to hit the horse with the strap just like other pets. 
That's how taming works for MyPet.

There is no option to have it on right clicks as that has some problems attached to it (canceling other right click actions can be... A pain)
