### ISSUE TITLE
shield right click lag

### ISSUE THREAD

**Issue by disqetow** [MyPetORG/MyPet#1571]
# Bug report

* [ ✔] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Install mypet on 1.19.2 server, when player keep right click shield like this video:
https://youtu.be/mzAuyQlIIPU
It cause player lag like video, big lag effect when player connect to you server 30ms++

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Install mypet lastest on 1.19.2 server 
2. join server and keep right click shield when someone attack you (monster or player)
...

## Expected behavior

It should not lag when player keep right click shield

## Actual behaviour

(https://youtu.be/mzAuyQlIIPU

**Bukkit/Spigot/Bungee Build/Version:*purpur 1.19.2 (all build have same problem)*

**MyPet Build/Version:*already try 1703、1702, same problem*

```

**Comment by Jakllp** [comment]
You tested without MyPet to confirm that it is because of MyPet?

**Comment by disqetow** [comment]
> You tested without MyPet to confirm that it is because of MyPet?

Yes, in fact I delete all plugin on my server, until I find which plugin cause this issue.
Very strange, but I am sure this issue related mypet.

**Comment by Jakllp** [comment]
Done in `3.12-SNAPSHOT-B1704`

Please keep your previous mypet version on hand as this update MIGHT in very rare cases cause some problems.
If so please report them immediately.
