### ISSUE TITLE
command bug

### ISSUE THREAD

**Issue by arkange83560** [MyPetORG/MyPet#1578]
hello I have a little problem with the plugin I'm in 1.19.1 I have version MyPet-3.12-SNAPSHOT-B1696 when I want to order /petshop it puts me as a message /petshop (name shop) when I delete my old file when it creates a new one i have no file pet shop ect just 3 file

**Comment by Jakllp** [comment]
What?

**Comment by arkange83560** [comment]
hello it was the request for my concern with the plugin, before you help me for the discord I put my request with my concern on the chanel help ;)
________________________________
De : Jakl ***@***.***>
Envoyé : samedi 24 septembre 2022 13:14
À : MyPetORG/MyPet ***@***.***>
Cc : arkange83560 ***@***.***>; Author ***@***.***>
Objet : Re: [MyPetORG/MyPet] command bug (Issue #1578)


What?

**Comment by Jakllp** [comment]
Resolved over Discord
