### ISSUE TITLE
how to get pet equipment?

### ISSUE THREAD

**Issue by HcFrostmorune** [MyPetORG/MyPet#1579]
I try to use the method "getMyPet().getOwner().getMyPet().getEntity().getEquipment().getArmorContents()" of event "MyPetInteractEvent" get it but return is null

i'm sorry,my english is poor

**Comment by Jakllp** [comment]
Ah yes...
You are accessing the Spigot-Side...
The thing is that getArmorContents isn't really functional for those and you'll have to access it via MyPetEquipment:

If you really just want the armor:
'((MyPetEquipment)event.getMyPet().getOwner().getMyPet()).getEquipment(EquipmentSlot.Helmet)'
And so on (for other armor slots)

If you just want... EVERYTHING you can do
'((MyPetEquipment)event.getMyPet().getOwner().getMyPet()).getEquipment()'

I hope this could help you if there are any more questions you can ask them here or you can close the issue if everything is cleared up ^^
