### ISSUE TITLE
Tadpole (Frog?) missing tongue sound

### ISSUE THREAD

**Issue by AnimeDrache** [MyPetORG/MyPet#1580]
# Bug report
I had no role on discord to post it there so I do it here =)
* [x] I have checked other issues to make sure this is not a duplicate.
definitely no dublicate
## Describe the bug
The attached file will explain it the best =). The "Tadpole"Pet is causing this issue.
_A clear and concise description of what the bug is._
An error message in the console
## To Reproduce
Just have an Tadpole Pet in use, walk few steps and wait for the error to appear in the console
_Steps to reproduce the behavior, please provide code snippets or a repository:_
As mentioned above

## Expected behavior
No error message
_A clear and concise description of what you expected to happen._
I think the Tadpole should do some frog noises?
## Actual behaviour
-
_If applicable, add screenshots to help explain your problem._
![Screenshot_9](https://user-images.githubusercontent.com/51856826/196015499-14cce471-ba53-4d5e-88f1-b8179c53164a.png)
## Additional context
-
> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/9793502/ticket.zip)
**Bukkit/Spigot/Bungee Build/Version:**
paper-1.19.2-210.jar
**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1718.jar

**What is the expected result?**
No error in the console
**What happens instead of that?**
An error occurs
**Error:**
[04:46:48 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Sound "entity.frog.tounge" not found. Please report this to the developer.
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
-

**Comment by Jakllp** [comment]
Note - This will be merged into the main project soon

**Comment by AnimeDrache** [comment]
Oki =)
