### ISSUE TITLE
After kill mobs got error message in console

### ISSUE THREAD

**Issue by Shadoworks** [MyPetORG/MyPet#1586]
# Bug report

* [ x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When killing animals or mobs and I follow the hunter job (JobsReborn plugin), I get an error message in the console (see below).

## To Reproduce

1. Install plugin JobsReborn
2. Install MyPets
3. Give permission to use JobsReborn and MyPets
4. Join the hunter job with /jobs join Hunter
5. Kill a Mob

## Expected behavior

No error message in the console.

## Actual behaviour

When killing animals or mobs and I follow the hunter job (JobsReborn plugin), the console keep clean.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/10095164/ticket.zip)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Paper
This server is running Pufferfish+ version git-PufferfishPlus-32 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: dc803d7 on HEAD)
You are on the latest version!
Previous version: git-PufferfishPlus-30 (MC: 1.19.2)

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1727

**What is the expected result?**
To make it work with the plugin JobsReborn

**What happens instead of that?**
An error in the console, because the two plugins use the same ressouce

**Error:**
```
https://pastebin.com/KwZnU23w
```

**Comment by Jakllp** [comment]
This is technically a bug on their end
