### ISSUE TITLE
Currently only admins can use it

### ISSUE THREAD

**Issue by neco222** [MyPetORG/MyPet#1590]
Can I use it online? Currently only admins can use it

**Comment by Jakllp** [comment]
I am confused. What do you mean "only admins can use it"

Like any plugin there are permissions.  
You can find them here: https://wiki.mypet-plugin.de/setup/permissions

**Comment by neco222** [comment]
I was able to solve it with the permission plugin. sorry for the late reply

**Comment by Jakllp** [comment]
Alrighty - Have fun with your pets ^^
