### ISSUE TITLE
 Crash problem

### ISSUE THREAD

**Issue by asdassafas** [MyPetORG/MyPet#1591]
In the Spigot1.12.2 version, opening the pet beacon will cause a seizure, which may cause a crash. The console does not report an error!

**Comment by asdassafas** [comment]
The longer the server is open, the greater the probability of service collapse

**Comment by asdassafas** [comment]
It is version 3.12, the latest version&nbsp;


2996378207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MyPetORG/MyPet]  Crash problem (Issue #1591)






您运行的是哪个版本的MyPet？

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by Jakllp** [comment]
I was not able to reproduce this  
On my test server the petbeacon-menu works as expected.

Could you use `/petbeacon` and then do `/petadmin ticket` and send over the zip file?

**Comment by asdassafas** [comment]
No, it seems that the longer the server runs, the longer it will be stuck&nbsp;


2996378207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月10日(星期二) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MyPetORG/MyPet]  Crash problem (Issue #1591)






我没能重现这个
在我的测试服务器上，pet beacon菜单按预期工作。

你能用/pet信标然后做/临时管理员把压缩文件发过来吗

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by Jakllp** [comment]
Stuck in what way?
Maybe you could record a video of the behavior you are describing as I cannot seem to reproduce it

**Comment by asdassafas** [comment]
When you enter/petbeacon to open the pet beacon, there will be stuck phenomenon, similar to thread blocking or network interruption. The time of stuck depends on the length of server operation or the length of pet use
&nbsp;


2996378207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月10日(星期二) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MyPetORG/MyPet]  Crash problem (Issue #1591)






卡在什么地方？
也许你可以把你描述的行为录下来，因为我似乎无法重现

—
直接回复此邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创作了该线程。留言ID:<my pet ***@***.***与&gt;.
