### ISSUE TITLE
If Mypet occurs in bedrock version

### ISSUE THREAD

**Issue by neco222** [MyPetORG/MyPet#1593]
# Bug report

* [ ✔] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

「Cannot jump or fly when using GeyserMc. When I try to jump/fly, I get down」

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

「Get off your pet when jumping or flying」

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
This is a limitation of the translation between Bedrock and Java.

Nothing we can fix.

**Comment by neco222** [comment]
Can't you fix it somehow?`
[ticket.zip](https://github.com/MyPetORG/MyPet/files/10400218/ticket.zip)
`

**Comment by Jakllp** [comment]
Sadly not.

The translation from java to bedrock has its limitations and that is one of them jothers are stuff like clickable chat things and stuff)
