### ISSUE TITLE
Money multiplier

### ISSUE THREAD

**Issue by 1saintlaur** [MyPetORG/MyPet#1595]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] 
## Is your feature request related to a problem? No

Add a way to add money multipliers to pets (pet-config).
Something like this:
MoneyMultiplier: 5 # (5%+)

**Bukkit/Spigot/Bungee Build/Version: 1.19.3**

**MyPet Build/Version: 3.12-SNAPSHOT-B1734**

**Comment by Jakllp** [comment]
What/when exactly would that money multiplier take effect?
Or are you just trying to change the price of a pet in `/petshop`?

**Comment by 1saintlaur** [comment]
We use ShopGUIPlus, and would like to multiple the sell price of different stuff when having some kind of pet equipped.

**Comment by Jakllp** [comment]
This seems like a very nieche usecase.  
I mean - you'd already have to somehow access that value using ShopGUIPlus (how would it know otherwise) so you probably also could just check the pet type the player has and do it that way.

**Comment by 1saintlaur** [comment]
I mean something like the plugin "Boosters" have, it multiplies every sell transaction somehow
