### ISSUE TITLE
Toggle Feature /pettoggle or /mypettoggle or /ptoggle

### ISSUE THREAD

**Issue by Grizzlybln** [MyPetORG/MyPet#1596]
# Feature request

What part of MyPet needs this?
- [×] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

- no its the first request i think

## Describe the solution you'd like

   I Will Request An Toggle-Feature , That Can User/Player Can Use for take off his pet
   The Pet Is Always Following The Player But, what is then the player have a shit-day and he is angry that the pet follow him,
   So He can use the /pettoggle to take off the following the pet will go to the switch gui and will wait of the /petcall use,
   If the player use /petcall the pet will go spawn and follow the player always 

## Describe alternatives you've considered

   Player will turn off the pet he use /pettoggle the pet is now sleeping in /petswitch GUI , if player use /petcall , the pet spawns

## Additional context

  I not have screenshots

**Bukkit/Spigot/Bungee Build/Version:**

   MyPet Build V3

**Comment by Jakllp** [comment]
Already there

`/petsendaway` aka `/psa` will just send it away into  the "active-slot" (it's not in the gui but can be called via `/petcall`)
And if you want it sent to the `/petswitch` GUI -> `/petstore`

**Comment by Grizzlybln** [comment]
Ok sorry

**Comment by Jakllp** [comment]
No problem, glad I could help ^^
