### ISSUE TITLE
Pets are all shown as pigs, but the function is normal

### ISSUE THREAD

**Issue by moshendian** [MyPetORG/MyPet#1598]
# Bug report

* I have checked other issues to make sure this is not a duplicate.

## Version

purpur 1.18.2
MyPet-3.12-B1737

_A clear and concise description of what the bug is._

## description

Pets are all shown as pigs, but the function is normal.

**Comment by Jakllp** [comment]
Please update your Citizens and then report back if the problem still persists

**Comment by moshendian** [comment]
The problem has been solved, thank you very much!

**Comment by pixkk** [comment]
Hello. I have same issue. Citizens version - 2.0.30, but all pets are pig.
Server version 1.16.5

**Comment by pixkk** [comment]
> The problem has been solved, thank you very much!

How you solve problem? Updated citizens?

**Comment by Jakllp** [comment]
> > The problem has been solved, thank you very much!
> 
> How you solve problem? Updated citizens?

Yea you'll want to uodate your citizens to their newest dev  build

**Comment by pixkk** [comment]
> 

Thx for the answer.
