### ISSUE TITLE
Piglin pets vibrate - Converted to Feature Request

### ISSUE THREAD

**Issue by Felina-Lain** [MyPetORG/MyPet#1599]
# Bug report - Converted to Feature Request, see comments

* [X ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Piglin pets vibrate as if they were about to Zombify. They don't, but they still vibrate.

## To Reproduce

Tame a piglin (adult, baby, brute), bring it to the overworld, wait and watch.

## Expected behavior

Previous versions did not vibrate. It's not gamebreaking, but it does makes me do a double take because I have this moment of "oh shit it's gonna die"

## Additional context

I get that the Overworld is probably a big change for them, but after a while I expect the excitation to die down and for them to stop vibrating with it XD

**Bukkit/Spigot/Bungee Build/Version:**

Paper1.19.2

**MyPet Build/Version:**

3.12-B1737

**Comment by Jakllp** [comment]
That's their normal behavior in the overworld.
There is a "noshake"-option for the `/petadmin create`-command that disables this.
But normal, tamed pets, will behave like their natural counterpart

**Comment by Felina-Lain** [comment]
> That's their normal behavior in the overworld. There is a "noshake"-option for the `/petadmin create`-command that disables this. But normal, tamed pets, will behave like their natural counterpart

I'm pretty sure they didn't before?
I've had this plugin on a server for more than a year now, had a baby piglin pet with it for around the same time, and it never vibrated in the overworld before. If it had, I'd have made a post on the subject a long time ago

I'll check out the command though, thanks

**Comment by Felina-Lain** [comment]
Hello again

The command to create new pets do work, BUT (and that's why it looked so weird to me, it clicked now) it doesn't make my old pets stop vibrating. Including my baby piglin which never vibrated before. (by command, or because when I installed the plugin with MyPet-3.12-SNAPSHOT-B1691, it didn't do it)

So I tried to downgrade to the version I had just before this update (MyPet-3.12-SNAPSHOT-B1704) and indeed, in that version my baby piglin doesn't vibrate.
New piglins I tame without the command do, but my already tamed baby doesn't. Yet when I update to 3.12-B1737, the baby also vibrate.

Is there a way to apply the command to existing pets? Or to... I dunno, clone them or something, with the command option?
Or some other way to stop them from vibrating when they're already tamed?

**Comment by Jakllp** [comment]
This is because previous versions of MyPet actually had a fault where they would track the baby status and also apply it to the noshake value (as that functionality wasn't identified yet)

I will convert this into a feature-request:
- Add a pet-config value for Nether-Pets to disable shake server-wide
