### ISSUE TITLE
[FR] Bentobox-Hook

### ISSUE THREAD

**Issue by Noogear** [MyPetORG/MyPet#1600]
# Feature-Request
Pets will ignore Bentobox's island protection to attack players

* [x] I have asked for help on other places like Discord ord the discussion on spigotmc.org

**Comment by RAURORA2** [comment]
And their pets also can kill the animals in other island

**Comment by Jakllp** [comment]
Not a question but a Feature Request:
- Create a hook for Bentobox

**Comment by RAURORA2** [comment]
> Not a question but a Feature Request:
> 
> * Create a hook for Bentobox

Through my test, I found that when a pet has control skills, it will cause the player to manipulate him to PVP on other people's islands. But if the control is deleted, when the player's pet on his island is attacked by another player, the fight back will not cause damage. Secondly, I found that the attack range of giants and ender dragons is problematic, and his attack range is shorter than the model.This is why i think it is a question.

**Comment by Jakllp** [comment]
The bentobox issue wipould still require a hook to resolve.

Giants and enderdragons are in the plugin for the fun of it. especially the enderdragon is quite complicated already and causes some form of trouble every single minecraft update (just for it to actually be a pet and to be able to interact with it).  
don’t expect a fix there very soon

**Comment by RAURORA2** [comment]
> The bentobox issue would still require a hook to resolve hence the FR
> 
> Giants and enderdragons are in the plugin for the fun of it. especially the enderdragon is quite complicated already and causes some form of trouble every single minecraft update (just for it to actually be a pet and to be able to interact with it). don’t expect a fix there very soon

For Ender Dragons and giants, is it possible to configure attack range in pet-config.yml? That would solve a big part of the problem.

**Comment by Jakllp** [comment]
Well it’s not currently an option but I can check how much hassle it is to implement

no promises tho
