### ISSUE TITLE
Please make this plugin support till 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [MyPetORG/MyPet#1605]
If possible, I would like to provide sponsorship to develop
I absolutely love this plugin! Hope to support 1.19.4 soon

**Comment by Jakllp** [comment]
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1738 already supports 1.19.4

**Comment by Jakllp** [comment]
And about the sponsorship: I’m flattered but bc of funny german laws I cannot accept it without major hurdles. 

thank you again tho!

**Comment by CCjun6** [comment]
ok you are a very good author
