### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by Jojokenn** [MyPetORG/MyPet#1607]
I cant find how to adopt pets without having op because only if i have op i can adopt them wih the kill form anyways i dont use the economy plugin because my friend cant adapt to use it

**Comment by Jakllp** [comment]
You can find a list of all available permissions and explanations on how they work here:  
https://wiki.mypet-plugin.de/setup/permissions

(but please don’t just copy paste everything but actually read the explanations and think about if you need that permission)

I’ll leave this issue open in case you have further questions, if you don’t feel free to close it yourself
