### ISSUE TITLE
Auto-Updater "latest Version files

### ISSUE THREAD

**Issue by capsload2** [MyPetORG/MyPet#1608]
Hey,

is there any way to have a direct DL link available without the version number?
That would be great for my latest update script.

https://github.com/MyPetORG/MyPet/releases/download/3.12-SNAPSHOT-B1738/MyPet-3.12-SNAPSHOT-B1738.jar

should be

https://github.com/MyPetORG/MyPet/releases/download/MyPet-latest.jar

Thanks :)

**Comment by Jakllp** [comment]
Well not really as this is just how github works.

MyPet has an auto-updater build in tho.
So you could just go ahead and enable that

**Comment by Jakllp** [comment]
(Does this resolve this issue?)
