### ISSUE TITLE
Wrong entity type display on Minecraft 1.16.5

### ISSUE THREAD

**Issue by MrXiaoM** [MyPetORG/MyPet#1610]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I have ran the latest release of MyPet on my server (Purpur 1.16.5).
It is strange that ALL kind of pet displayed as a `PIG`, which shows the entity type is `UNKNOWN`.
(After my testing. The value of `entity.getType().name().toUpperCase()` is `UNKNOWN`)
But when you release the pet, it will summon an entity with the right type.

I tried to [hard-encode the entity type](https://github.com/MrXiaoM/MyPet/commit/dbd6d6ef73f2e3aff31690522ef2dc2c68111464), it works. It shows the right entity type now.
I guess there is something wrong with `EntityRegistry`.

## To Reproduce

Install MyPet on Purpur 1.16.5. I have not test on other fork of Paper.

## Expected behavior

Pet must be displayed as their set type.

## Actual behaviour

All pet displayed as a pig.

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** Purpur 1.16.5 (v1_16_R3)

**MyPet Build/Version:** 3.12-SNAPSHOT-B1740

**Comment by Jakllp** [comment]
Are you using Citizens by any chance?

**Comment by Jakllp** [comment]
The "UNKNOWN" bit is intentional btw as we do not want other plugins to handle a mypet-pig like an ordinary pig (which is why the EntityRegistry actually registers new Entities in the Vanilla-Registry)

**Comment by Jakllp** [comment]
Is this still an issue?

**Comment by MrXiaoM** [comment]
Sorry for waiting so long. It was caused by my modified-Purpur. I have fixed it myself. I apologize for any inconvenience that may have caused you.

**Comment by Jakllp** [comment]
Glad the issue could be solved
