### ISSUE TITLE
Does not work in Arclight 1.18.2

### ISSUE THREAD

**Issue by DaDiGui** [MyPetORG/MyPet#1611]
> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
https://pastebin.com/YWsXuYfM

**Bukkit/Spigot/Bungee Build/Version:**
arclight-forge-1.18.2-1.0.8

**MyPet Build/Version:**
MyPet v3.12

**What happens instead of that?**
The commands are registered when I tab but none of them work. Also when I run them I don't get any kind of error in console/chat ingame. Leads do not work. In short, nothing works but it detects that the plugin has loaded.

**Error:**
https://pastebin.com/i92GQDQs

**Comment by Jakllp** [comment]
Not a bug.

MyPet is only supposed to work with Spigot/Paper.
Spigot-Forge Hybrids are all handling entity registration differently so it would need extensive work for every single one of them.

**Comment by Zergiv** [comment]
any alternative to mypet?
