### ISSUE TITLE
Pet Inventory in Mob Arena

### ISSUE THREAD

**Issue by Troublemaker141** [MyPetORG/MyPet#1614]
# Bug report

* [x ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When you fight in a Mob Arena with you pet you can put your gear inside the pets inventory and get this gear outside the arena.

## To Reproduce

Working with official mob arena plugin

## Expected behavior

Block inventory in arena.

## Actual behaviour

You can open the inventory as usual.

**Comment by Jakllp** [comment]
You could disable the command in that area
