### ISSUE TITLE
Range Fire Rate on dynamic level

### ISSUE THREAD

**Issue by Troublemaker141** [MyPetORG/MyPet#1616]
# Question about MyPet

How to setup the fire rate on the range skill correctly?

Because if i set it to +5 the pet will shoot slightly slower per level.
And if i set it to -5 the fire rate sometimes becomses weird like -300 shots?

* [ ] I have asked for help on other places like Discord ord the discussion on spigotmc.org

**Comment by Jakllp** [comment]
Hey, sorry for the late answer.

The fire-rate is admittedly a bit tricky and I had to test some stuff myself just to be sure that I can explain it right:  
Basically: As the skilltree-editor says it's x50ms -> shots/second  
WHICH isn't completely right (in my opinion but I don't know how to do it better so yea...)

From a technical standpoint 20 shots per second (one per tick) is the fastest you can shoot. That would be 1200 Rounds/minute.

You can achieve this by having 0 as your fire-rate. I think (I honestly haven't looked at the code but that is what I can deduce from the outside) it basically calculates this:  
`fire_rate + 1 * 50ms` as the delay inbetween shots.  
Everyting below 0 will result in infinity/negative values -> Shoots every second

This means that the value of 1 in the fire-rate produces a shot every 2 ticks -> 10 times per second, 600 per minute.

This means that you want to start with a slow fire-rate -> high value and then do a subtraction in the dynamic part of the skilltree.

For example (rounds/min according to `/petskill`:
```
Level 1: fire_rate +50 -> 23,53 rounds/min

From level 5 every 5 levels:
fire_rate -5 -> 26.09 rounds/min at level 5
-> 38.71 rounds/min at level 20
```
This is just some random skilltree with slow increments tho. Balancing is on you.

I hope I could help, if you have any other questions feel free to ask
