### ISSUE TITLE
Please update to 1.20

### ISSUE THREAD

**Issue by CCjun6** [MyPetORG/MyPet#1623]
I really like this plugin
But it doesn't work properly in version 1.20
Please update the author if you have time

**Comment by Jakllp** [comment]
The newest build ([B1741](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1741)) starts in 1.20

It does not have the new mobs as pets yet, but it starts.  
Did you use that build?  
If so and it didn't start please paste the error.
