### ISSUE TITLE
/petshop command bug

### ISSUE THREAD

**Issue by deHasher** [MyPetORG/MyPet#1624]
**Bukkit/Spigot/Bungee Build/Version:**
git-Purpur-1171 (MC: 1.16.5)

**MyPet Build/Version:**
3.12-SNAPSHOT-B1741

**What is the expected result?**
The purchased pet must match its type that was purchased

**What happens instead of that?**
When buying a pet in mypet shop, the purchased pet becomes a pig

**Comment by Jakllp** [comment]
Are you using citizens?

**Comment by deHasher** [comment]
> Are you using citizens?

Yes

**Comment by deHasher** [comment]
> Are you using citizens?

If it's because of citizens, then what plugin can it be replaced with?

**Comment by Jakllp** [comment]
It *should* just work with the newest citizens versions.  
Try that first

**Comment by Jakllp** [comment]
Did that solve your issue?

**Comment by deHasher** [comment]
> Did that solve your issue?

Yes, thank you for help! ^^
