### ISSUE TITLE
Kindly Add the Sniffer and update the plugin to 1.20

### ISSUE THREAD

**Issue by INFINITEMINECRAFTER** [MyPetORG/MyPet#1626]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

_Its a request_

## Describe the solution you'd like

_Id like this to be updated to 1.20 and to be supporting a sniffer._

## Describe alternatives you've considered

_No alternatives unless ill need to create a plugin myself._

## Additional context

_-_

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Comment by Jakllp** [comment]
1.20 is already supported, the new mobs haven't been implemented yet tho.  
I just didn't have the time yet

**Comment by rebeccarochelle22** [comment]
Do we have an estimated timeframe for adding the new mobs? Not rushing, just curious

**Comment by Jakllp** [comment]
Done in the latest release:  
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1743
