### ISSUE TITLE
Pets not attacking 

### ISSUE THREAD

**Issue by Sadsoul091** [MyPetORG/MyPet#1628]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
This is way too generic. 
What aren't they attacking? 
What are the circumstances? (e.g. is the owner being attacked but the pet just... Waits)  
Are they in a petbehavior? 
Which skills do they have? (they might not even have an attack skill or maybe aren't high enough in level)  
Which version of Minecraft?
Etc

**Comment by Sadsoul091** [comment]
Actually they are attacking but not giving damage only ranged attacks r giving damage but melee attacks doesn't even after I set /pet to duel 
Minecraft versus 1.20

**Comment by Jakllp** [comment]
Did you check if they have melee attacks?  
Can you send a screenshot of what `/petskill` outputs?
