### ISSUE TITLE
Riding pet glitch, unmounting tp you back

### ISSUE THREAD

**Issue by Felina-Lain** [MyPetORG/MyPet#1630]
# Bug report

* [ X] I have checked other issues to make sure this is not a duplicate.  (it technically is, but the other issue is way old, and the solution for it was to update the plugin, but I'm already using the latest version this time)

## Describe the bug

I tamed a horse, set it to riding skill tree, right clicked it with the riding item. I got on it fine (I couldn't open my inventory though, but I can't remember if that's normal or not? I would say not, but I'm unsure)
But when I started going with it:
- it glitched when I reached the end of the loaded chunks. Not just because the chunk didn't load, they did. The horse just started stuttering on the spot, with me on it, until I dismounted.
- dismounting tp-ed me back to where I mounted

## Expected behavior
- the horse doesn't glitch when reaching the end of loaded chunk
- dismounting doesn't tp you back, but keep you where you dismount

## Additional context
[ticket.zip](https://github.com/MyPetORG/MyPet/files/12073907/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
paper-1.20.1-83

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1741

I'm on the latest paper, and plugin version, this happens only with horses as far as I tested. (I tried making a rideable zombie, and a rideable creeper, there was no problems).
If you need any other info that I can send, I'll send

**Comment by Jakllp** [comment]
Thought you might not have had `Throw-PlayerMoveEvent-While-Riding` enabled, but you do.  
Will have to check if this is a general riding issue in 1.20 OR maybe an issue with the riding system for pets that need a seat (internal thing for stuff like horses, pigs, striders etc aka everything that is rideable ingame - and the Ravager for some reason)

Thanks for the report!

**Comment by Felina-Lain** [comment]
I just thought: maybe they changed something with riding because they added the camel?
I've tried with the others rideable mobs you mentioned:

- Pig: could get on, couldn't drive it. It just never moved when I was on it, not with a stick-carrot, not even without at random
- Strider: could be driven just fine, but had the tp-back bug, unmounting would tp me back
- Ravager: Would not move when I was on it. I'm not aware of any item to try force it, so it just never moved.
- Camel: were not tameable with the plugin yet

**Comment by Jakllp** [comment]
Fixed in the latest release:  
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1743

Your suspicion was kinda right - they changed some riding things - not necessarily for the camel but still.  
Good thinking ^^
