### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by XxGalaxy300** [MyPetORG/MyPet#1631]
How to add essentialsX economy to the petstore
I cant add it

**Comment by Jakllp** [comment]
As long as you have Vault installed it should just work without having todo anything else.

There should be a block of mypet-messages on server boot and one should mention economy

**Comment by XxGalaxy300** [comment]
I have jnstalled it
![Screenshot_20230719-233001_Brave](https://github.com/MyPetORG/MyPet/assets/125708368/8015f7c8-fe27-46b4-af7d-d2ab87ba7880)

**Comment by Jakllp** [comment]
So is it fixed or not? 
If not: Please do `/petadmin ticket` and send the zip file that is created

**Comment by XxGalaxy300** [comment]
Heres the mypet log
[9UTCB54Q.txt](https://github.com/MyPetORG/MyPet/files/12100318/9UTCB54Q.txt)

**Comment by Haeherfeder** [comment]
> /petadmin ticket

in your mc server, and then send the resulting file
