### ISSUE TITLE
Creacion de la mascota Camello

### ISSUE THREAD

**Issue by Sammyi15** [MyPetORG/MyPet#1633]
Quisiera saber como puedo agregar una nueva mascota, quiero decir que en su configuración default no está el camello (ID: CAMEL), quisiera crear para que puedan "tamearlo y usarlo como mascota" pero no he podido. 
Quisiera un poco de su ayuda.

**Comment by Haeherfeder** [comment]
look at the last release message:

```
3.12-SNAPSHOT-B1741  - Basic 1.20 compatibility

New:
Added basic 1.20(.1) compatibility*

*What is meant by basic: It runs and it seems to work as expected.
The new mobs have NOT been added yet and will follow soonish.
There might be bugs as 1.20(.1) is still new - please report them over in ⁠bug-reports and mention 1.20. Thanks.

```

**Comment by Jakllp** [comment]
Done in the latest release:  
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1743

**Comment by Jakllp** [comment]
Please update your Purpur.  
Spigot/Paper/purpur made changes and MyPet had to adapt as well. This results in the plugin only working with the new versions anymore
