### ISSUE TITLE
Players can't tame more than one pet

### ISSUE THREAD

**Issue by windstormb** [MyPetORG/MyPet#1634]
# Explain your question

* [ ] I have checked existing issue and found none that could answer my question.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._

> I encourage you to try and make an issue with one of the other templates before submitting the general form.

I can't get players on my server to tame 2 or more pets. Everytime they try to it comes up with the message "You already have a pet". I've tried increasing the limit in configs and enabled the perms to allow them to tame a second pet however it still pops up with the same message. I don't know if I'm modifying the wrong area for this, can you please tell me where I'm going wrong
![image](https://github.com/MyPetORG/MyPet/assets/140659012/2979b09b-bec6-4873-8fc2-32e6ae7c4dd8)

**Comment by Jakllp** [comment]
They can't have more than one ACTIVE pet. They'll need to store their pet via `/petstore`

They can then select stored pets with `/petswitch`
