### ISSUE TITLE
Drowned Entity can drown

### ISSUE THREAD

**Issue by MaksyKun** [MyPetORG/MyPet#1635]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

It's just that drowned entities can drown. It was reported on our server since dolphins dont drown at all and they wished to have the same possibility for drowned.

```

**Comment by Jakllp** [comment]
How did they even get them underwater? They should swim.

In any case: Yea, they shouldn't, good catch

**Comment by MaksyKun** [comment]
Tbh, I dont know xD
Sometime people become creative I guess.

**Comment by Jakllp** [comment]
Done with latest release:  
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1743
