### ISSUE TITLE
How do I allow players to summon more than one pet?

### ISSUE THREAD

**Issue by windstormb** [MyPetORG/MyPet#1636]
# Explain your question

* [ ] I have checked existing issue and found none that could answer my question.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._

> I encourage you to try and make an issue with one of the other templates before submitting the general form.

I want players to summon as many pets as they want as opposed to one

**Comment by Jakllp** [comment]
This is not supported
