### ISSUE TITLE
No Pets appearing

### ISSUE THREAD

**Issue by markie1611** [MyPetORG/MyPet#1642]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

MyPet looks like its loading in the console fine, and I can action pets, but the pet mob doesn't load, its not possible to /petcall without getting an error, and there is an error in the console.

I had MyPet working, played with the config a bit, and it broke. So I have uninstalled the plugin and reinstalled with no edits and it is still doing the same. 

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Install MyPet
2. Reload server
3. Buy Pet
4. (No pet arrives) although the pet is registered to me
5. /petcall - error "An Internal error occurred while attempting to perform this command"

## Expected behavior

A pet to arrive

## Actual behaviour

No pet and errors

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/12571042/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**  
Spigot Paper 1.20.1

**MyPet Build/Version:** 
MyPet-3.12-SNAPSHOT-B1745.jar

**What is the expected result?**
Pet to appear
**What happens instead of that?**
Error message

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
[errorlog.txt](https://github.com/MyPetORG/MyPet/files/12571044/errorlog.txt)

**Comment by Jakllp** [comment]
Update your paper

**Comment by markie1611** [comment]
Hello, I was running build 172, and have now updated to the latest 174, but the problem persists. Would you mind reopening this ticket and taking another look. Many Thanks

**Comment by Jakllp** [comment]
In the ticket you sent you were running `git-Paper-96`

Please make sure your server host (or your start script if self hosted) is actually using the paper.jar.

I have seen cases where it uses a `server.jar` or something like that to actually run the game.

You can check which version of paper is running by looking at your server-log at boot-up.  
In your ticket the first view lines look like this:
```
[23:35:39] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:35:40] [ServerMain/INFO]: Loaded 7 recipes
[23:35:41] [Server thread/INFO]: Starting minecraft server version 1.20.1
[23:35:41] [Server thread/INFO]: Loading properties
[23:35:41] [Server thread/INFO]: This server is running Paper version git-Paper-96 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b14979e)
```
As you can see in the last line: You were running Paper Build 96 there

**Comment by markie1611** [comment]
I appreciate what your saying, but I beleive I'm trying to run the correct version (i've added a screenshot where it shows build #174 at the top of the console, and then shows git-paper-96 further down). 
![errorlog](https://github.com/MyPetORG/MyPet/assets/21036524/44468164-419d-428d-a152-54db6b1cac83)

I have resolved my current problem by depreciating MyPet to build #1743 as you mentioned to do on the discord, and that has fixed it. 

I can see i'm not the only one experiencing this, so if there is any information I can provide to you to help you fix the problem on future builds please let me know and i'll send it in. 

thank you for your quick responses and all you do with this plugin.

**Comment by Jakllp** [comment]
You are using Multicraft.  
Multicraft is loading the config for Paper 174 but is then not actually loading 174 but 96.

I have not worked with multicraft before personally but I believe that this could be one of three things:
- Either the Multicraft-Config is just named 174 but the version setting inside the config is still 96
- Maybe the Multicraft-Config is still configured to load the 96 paper-jar (in this case there would be multiple jar files in your minecraft-server-directory and it is still set to use the old one)
- Maybe the jar that it is trying to load needs to be replaced and not just the config but it never has been replaced with a newly downloaded paper-jar

**Comment by markie1611** [comment]
I should have updated and said you were right, after running a custom jar it loaded to the correct version and MyPets worked again. Many Thanks
