### ISSUE TITLE
NoSuchMethodException in MyPet 3.12 b1746 on Paper 1.20.2

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1646]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

We've just updated to Paper 1.20.2 and have been getting the following error spammed in console: https://gist.github.com/mercurialmusic/ee35b6cf13bc560e8bec12e8e1302972 

## Actual behaviour

In-game plugin behavior doesn't seem to be affected, or at least if it is we haven't discovered it yet.

**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-241 (MC: 1.20.2)
**MyPet Build/Version:**
MyPet 3.12 b1746

Thanks!

**Comment by Jakllp** [comment]
Fixed in b1747  
https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1747

**Comment by mercurialmusic** [comment]
Thank you!
