### ISSUE TITLE
Players riding a Warden are teleported back to the pet's location when something else teleports them away

### ISSUE THREAD

**Issue by MrPowerGamerBR** [MyPetORG/MyPet#1647]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Players riding a Warden are teleported back to the pet's location when something else teleports them away.

This happens due to this code in the `EntityMyPet` class
```java
		if (hasRider) {
			if (!isVehicle()) {
				hasRider = false;
				this.setMaxUpStep(0.5F); // climb height -> halfslab
				Location playerLoc = getOwner().getPlayer().getLocation();
				Location petLoc = getBukkitEntity().getLocation();
				petLoc.setYaw(playerLoc.getYaw());
				petLoc.setPitch(playerLoc.getPitch());
				getOwner().getPlayer().teleport(petLoc);
			}
		} else {
```

When riding a Warden + getting teleported somewhere else, the `hasRider` flag is true but the `isVehicle` check is false, this causes you to teleport to the pet's location after unmounting.

This affects normal teleports (except if you are teleporting into a unloaded chunks) and cross world teleports.

https://cdn.discordapp.com/attachments/739823666891849729/1172334646332244068/javaw_wV4Tluga81.mp4

(Notice how even tho I'm attempting to teleport to another world, I'm always getting back to where I was)

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Ride a Warden
2. Attempt to teleport to somewhere else

## Expected behavior

You are teleported to the target location.

## Actual behaviour

You are teleported to the pet's location.

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:** This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version
Previous version: git-SparklyPaper-"049a8e5" (MC: 1.20.2)

**MyPet Build/Version:** b#1747

**Error:**
*no error*

**Comment by Jakllp** [comment]
Well written, nice that you already included the part of code where the error lies.  
This is caused by the digging-animation as the warden sticks around longer than normal pets. Good catch.  

Will need to work around that, expect an update soon

**Comment by Jakllp** [comment]
Yea I cannot replicate this behavior as the Warden gets teleported with the player (see https://github.com/MyPetORG/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/listeners/PlayerListener.java#L398)  

Do you have anything configured that might prevent this from happening (see the code)?

**Comment by Jakllp** [comment]
Funnily enough this code doesn't work properly anymore?  
Yayy

**Comment by Jakllp** [comment]
I cannot replicate this behavior as this code should prevent whatever is happening on your server:  
https://github.com/MyPetORG/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/listeners/PlayerListener.java#L416  

Do you have any plugins installed that could prevent this code from working properly?

**Comment by MrPowerGamerBR** [comment]
@Jakllp sorry for the late response!

I was able to reproduce the bug with MyPet and Multiverse-Core installed, running Paper version git-Paper-290 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f186318)

**Comment by MrPowerGamerBR** [comment]
https://github.com/MyPetORG/MyPet/assets/9496359/a7960f09-c2a3-44e1-865c-2c784f385867

**Comment by C0dezin** [comment]
I was able to replicate the behavior on a localhost server with mypet and multiverse-core only. Running on Paper version git-Paper-292 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 0a8c873)

[ticket.zip](https://github.com/MyPetORG/MyPet/files/13400787/ticket.zip)

**Comment by C0dezin** [comment]
https://github.com/MyPetORG/MyPet/assets/73194980/23d79bb3-6089-44e7-8025-eac9f32e1590
