### ISSUE TITLE
MyPet ClassCastException 

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1656]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I've been randomly getting this error in console: https://gist.github.com/mercurialmusic/9469c10401e45c3ed6710880157e0924
I'm unsure if it's affecting anything in game. I have not been able to reproduce it and players haven't been complaining about anything (yet).

I did not notice the error until recently, so I'm guessing it's a Spigot/Paper change messing with things.

## Additional context

**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-430 (MC: 1.20.4)

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1756

**Comment by Jakllp** [comment]
Fixed via https://github.com/MyPetORG/MyPet/commit/253f14a5690e48cc4be6711c2a43635ec7c15d5a in https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1757
