### ISSUE TITLE
Cross-Server Compability

### ISSUE THREAD

**Issue by Leahcimkrob** [MyPetORG/MyPet#1657]
Is it possible to add cross-server functionality, e.g. via Redis?
I mean that you buy a pet on one server and then have it on the second server.

**Comment by Jakllp** [comment]
You'll just have to configure your database to the same one.  
By default MyPet uses SQLite locally but you can configure it to use a MySQL or MongoDB Database which can be shared between multiple servers.

I'll leave this open for now. If this answered your question feel free to close the issue.

**Comment by Leahcimkrob** [comment]
That didn't work yesterday, but it was human error. The colleague who tested it didn't try to spawn the pet with switch. If you don't do everything yourself...

**Comment by Jakllp** [comment]
All good, glad it worked!
