### ISSUE TITLE
mypet will not work on MC 1.20.6

### ISSUE THREAD

**Issue by Leahcimkrob** [MyPetORG/MyPet#1664]
mypet will not work on MC 1.20.6

We get this message:

05-14-2024 12:00 [INFO] [MyPet] Error-Reporter ENABLED
05-14-2024 12:00 [INFO] [MyPet] Enabling MyPet v3.12
05-14-2024 12:00 [INFO] [MyPet] No Update available.
05-14-2024 12:00 [WARNING] [MyPet] This version of MyPet is not compatible with "null on 1.20.6". Is MyPet up to date?

**Comment by Jakllp** [comment]
Yes, it has not been updated yet.

**Comment by Leahcimkrob** [comment]
Will there be another update? Or can we remove the plugin from the server again?

**Comment by Jakllp** [comment]
There will be an update I cannot say when exactly yet as I am quite busy

**Comment by RandalABurdJr** [comment]
I really hope it is updated, because it is my buddy's favority plugin. :D

**Comment by Dreadonator** [comment]
@Jakllp do you have any news on the process or any idea when you will update?

**Comment by Jakllp** [comment]
Done with this release: [3.12-SNAPSHOT-B1760](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1760)
