### ISSUE TITLE
Request a new update for 1.20.6

### ISSUE THREAD

**Issue by Rebines** [MyPetORG/MyPet#1668]
# Feature request

What part of MyPet needs this?
 the plugin itself

## Is your feature request related to a problem? Please describe

The latest version is not compatible with 1.20.6

## Describe the solution you'd like

Other pets plugins,but their effects is compeletly different

## Describe alternatives you've considered

A new update for 1.20.6

## Additional context

![image](https://github.com/user-attachments/assets/ff11f938-597a-4c60-8da2-a4c516b2c7b5)

**Bukkit/Spigot/Bungee Build/Version:v1_20_R4 - 1.20.6 - paper  1.20.6-2233-0d6766e (MC: 1.20.6)**

**MyPet Build/Version:3.12-SNAPSHOT-B1757**

**Comment by Dreadonator** [comment]
I can confirm

**Comment by ScuroK** [comment]
Yup

**Comment by Jakllp** [comment]
Done with this release: [3.12-SNAPSHOT-B1760](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1760)
