### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by SrCassiani** [MyPetORG/MyPet#1669]
Could you update the version? It just doesn't catch me on my server and I think it's because it's outdated and the pl is very good

**Comment by Jakllp** [comment]
I don't really know what you mean by that but if you mean 1.20.6 or 1.21 support: I updated it legitimately a few minutes before your issue: [3.12-SNAPSHOT-B1760](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1760)  

Is that what you meant?

**Comment by SrCassiani** [comment]
Yes, I have the latest version on my server and the plugin doesn't work for me.

**Comment by Jakllp** [comment]
Well can you provide more context other than "it doesn't work"

- Server Software (so spigot/paper/etc)
- Server Version
- MyPet Build (the number behind the b so something like b1760)
- Is there any error message about MyPet when you start your server? If so send it

**Comment by Jakllp** [comment]
And you can try again with [Build 1762](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1762)
