### ISSUE TITLE
Compatibility with LevelledMobs 4

### ISSUE THREAD

**Issue by chillgerne89** [MyPetORG/MyPet#1672]
# Bug report

* [ +] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

In addition to MyPet, I also use the plugin LevelledMobs 4.0.6 B35. LevelledMobs recognizes the pets as mobs that need to be leveled. As a result, the name tag is replaced, and an incorrect level and incorrect HP are displayed. When riding the pet, you have the correct amount of life, but it shows that the pet could have more life. In addition, the remaining life changes back and forth all the time.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Install Paper 1.20.6 Build 147 with MyPet 3.12 B1761 and LevelledMobs 4.0.6 B35
2. Start the Server
3. Call a Pet and see the Nametag or ride a Pet

## Expected behavior

Is it possible for the pets from MyPet to be ignored by LevelledMobs?

## Actual behaviour
![Screenshot 2024-07-16 083013](https://github.com/user-attachments/assets/06f71abe-d60b-4f9e-91e0-03dfe4a8f4d9)
![Screenshot 2024-07-16 083029](https://github.com/user-attachments/assets/bbc5bdc7-c0fd-491e-8ee1-3bc1a4b7c94c)

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** Paper 1.20.6 Build 147

**MyPet Build/Version:** 3.12 B1761

**What is the expected result?** Show MyPet Nametag and ignored by LeveledMobs

**What happens instead of that?** Show LevelledMobs Nametag with wrong Level and HP

There is no Errorcode

**Comment by Jakllp** [comment]
As far as I know this is mostly on LevelledMobs-Part and I think they even have an ability in their config to ignore MyPet-Pets.

**Comment by Jakllp** [comment]
This was for LevelledMobs 3 but I expect there to be similar functionality in 4 (this was a statement by a LevelledMobs-Dev afaik):
```
locate this in rules.yml mob-customname-status: EITHER
change to mob-customname-status: NOT_NAMETAGGED
then run /lm rules force_all
```

**Comment by chillgerne89** [comment]
I tried it, and it seems to work. Thank you.
