### ISSUE TITLE
Switching to pets with existing items in their inventories not working

### ISSUE THREAD

**Issue by FredoJF** [MyPetORG/MyPet#1673]
# Bug report

* [✓] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Switching to pets with existing items in their inventories not working.

## To Reproduce

1. use `/petswitch` command
2. click on a pet with existing items in its inventory

## Expected behavior

The pet appears.
(switching to a pet without any item in its inventory works.)

## Actual behaviour

The pet is not appearing.

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** Paper 1.21 build 77

**MyPet Build/Version:** [3.12-SNAPSHOT-B1762](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1762)

**Error:** https://pastebin.com/TZYfbvnC

**Comment by rafaelflromao** [comment]
Did you recently upgrade your server from an older version?

**Comment by Jakllp** [comment]
Fixed with [Build 1763](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1763)
