### ISSUE TITLE
宠物背包

### ISSUE THREAD

**Issue by Aclur** [MyPetORG/MyPet#1674]
服务器随意关闭宠物背包，大量物品消失怎么办

**Comment by Jakllp** [comment]
I'm guessing you are running 1.20.6 or 1.21
Petinventory is bugged on those versions right now. Wait for a fix.

**Comment by Jakllp** [comment]
Fixed with [Build 1763](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1763)
