### ISSUE TITLE
New 1.21 entity types not supported as pet types yet?

### ISSUE THREAD

**Issue by BigScary** [MyPetORG/MyPet#1675]
# Bug report

* [ Yes ] I have checked other issues to make sure this is not a duplicate.

Searched, but didn't spot it from bug titles.

## Describe the bug

Several new entity types were added in 1.21. Players are unable to tame them, I'm unable to /petadmin create pets of those types, either.

## To Reproduce

/petadmin create <player name> Armadillo

## Expected behavior

I have a new pet in /petswitch menu of Armadillo type.

## Actual behaviour

Unknown pet type error

## Additional context

I tried manually adding the Armadillo to the pets config file, but that wasn't enough to fix it.

**Bukkit/Spigot/Bungee Build/Version:**

Paper 1.21 Build 108

**MyPet Build/Version:**

[3.12-SNAPSHOT-B1762](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1762)

**Comment by Jakllp** [comment]
Correct.  
They have not been implemented yet.

**Comment by Jakllp** [comment]
Forgot to mention:  
Done in [3.12-SNAPSHOT-B1769](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1769)
