### ISSUE TITLE
Causa conflipto con el ProtocoLib y Proboca mucha cantidad de LAG 

### ISSUE THREAD

**Issue by JackXOtaku** [MyPetORG/MyPet#1676]
![image](https://github.com/user-attachments/assets/6f6c7723-cda7-435a-b68c-bde56ba71ef8)

Tengo ese problema y me hace que el ProtocoLib se sature y lagea todo el server. 

No entiendo por que seria ese error.

**Comment by Jakllp** [comment]
Minecraft-Version?  
Server-Type?  
MyPet-Build?
