### ISSUE TITLE
Wolf.Variant class is not properly taken on pet-leash

### ISSUE THREAD

**Issue by MaksyKun** [MyPetORG/MyPet#1681]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
1. The 9 different variants of wolves are also becoming the "vanilla" wolf when capturing it. Instead it should be the variant.
2. Furthermore, when releasing the default wolf in a proper biome, he becomes the variant of the wolf-types.
## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_
1. Capture any wolf, it will become normal type
2. Release a wolf in the desired biome, it will become the other variant

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
It should have a possibility to stpre Wolf.Variant Class of the new wolves from 1.20.6+

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: git-Purpur-2176 (MC: 1.20.4)

**MyPet Build/Version:**
MyPet  3.12

**Comment by mercurialmusic** [comment]
Confirming. Seems like it's doing the same for the cats as well. Pets change to the default wolf or random cat when leashed, then at least with cats seem to change variants randomly.

Using 3.12-SNAPSHOT-B1765 on Paper version 1.21.1-40

**Comment by Jakllp** [comment]
Was done in https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1774
