### ISSUE TITLE
All players will be thrown out when killed by pets

### ISSUE THREAD

**Issue by EncVar** [MyPetORG/MyPet#1683]
# Bug report

- [x]   I have checked other issues to make sure this is not a duplicate.

## Describe the bug

All players will be thrown out when killed by pets

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Attack one player's pet
2. Killed by other player's pet

## Expected behavior

Killed player respawns.

## Actual behaviour

Disconnect to the server (All players)

## Additional context

This issue is uploaded by player. I have no permission to get ticket and version info.

**Bukkit/Spigot/Bungee Build/Version:**
Bukkit server running Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
[disconnect-2024-08-24_22.13.17-client.txt](https://github.com/user-attachments/files/16739946/disconnect-2024-08-24_22.13.17-client.txt)
```

**Comment by Jakllp** [comment]
Will check

**Comment by Jakllp** [comment]
Does this also happen on 1.21.1?

**Comment by Jakllp** [comment]
It seems that this is a 1.21 issue, which isn't officially supported.

As 1.21.1 is an important update AND this does not happen on 1.21.1.

Please update
