### ISSUE TITLE
JS cant work

### ISSUE THREAD

**Issue by 404forever1** [MyPetORG/MyPet#1685]
![image](https://github.com/user-attachments/assets/13a1aa6a-5914-4948-a668-e5fd5081e553)
![image](https://github.com/user-attachments/assets/ae5e8a80-dab0-4088-9e88-83838ad15eaa)
![image](https://github.com/user-attachments/assets/1e733d21-3a32-458e-a6ec-ba3f8d256c19)

**Comment by Jakllp** [comment]
This is a problem due to paper.  
There is a workaround for now:  
In your plugins-folder there is a .paper-remapped folder.
Create a MyPet folder in there, put the rhino.jar inside of there

**Comment by Jakllp** [comment]
Fixed in [3.12-SNAPSHOT-B1768](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1768)
