### ISSUE TITLE
1.19+ Crash Bug

### ISSUE THREAD

**Issue by Kowaman** [MyPetORG/MyPet#1686]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

MyPet appears to have a server crash bug in 1.20.6 and 1.21 (haven't tested earlier versions, but the code that causes this appears to be a 1.19+ listener): https://mclo.gs/vtzhHcV

It looks like it blocks a netty thread while it asks for the main thread to do some entity related logic on the Clientbound use entity packet, however the main thread may at the same time be blocked while it is waiting on a netty thread to to setup a new player, if this is the same netty thread it creates a deadlock.

Main thread freeze: https://mclo.gs/vtzhHcV#L913
MyPet calling the main thread from the netty thread: https://mclo.gs/vtzhHcV#L3359
MyPet throwing an warning once server initiates shutdown: https://mclo.gs/vtzhHcV#L3844 

Problematic line of code (though anything calling `ensureMainThread` within a packet listener will likely cause this issue): https://github.com/MyPetORG/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/util/hooks/ProtocolLibHook.java#L139

## To Reproduce

1. Have players log in while entities are being interacted with.
2. Is a bit random due to the amount of netty threads, the blocked thread needs to be the same thread that the main server thread is waiting on.

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** Purpur 1.21.1-2308-ver/1.21.1@8332fa4

**MyPet Build/Version:**  MyPet-3.12-SNAPSHOT-B1765

**Comment by Jakllp** [comment]
I included the PR (#1687) in [3.12-SNAPSHOT-B1768](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1768) so it can now be tested

**Comment by Kowaman** [comment]
@Jakllp been testing on my server, all looks good! thank you!
