### ISSUE TITLE
placeholder pet's favorites food

### ISSUE THREAD

**Issue by HomyakCMD** [MyPetORG/MyPet#1688]
It is possible to display your pet’s favorite food in the TAB plugin?

**Comment by Jakllp** [comment]
This already exists - the placeholder "petfood".  
For a *kinda* list of all placeholders see this file:  
https://github.com/MyPetORG/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/util/hooks/PlaceholderApiHook.java

It's the actual code so not as readable but you can basically search for `placeHolders.put` and you will find all placeholders mypet has

**Comment by Jakllp** [comment]
Will have to update https://wiki.mypet-plugin.de/hooks/placeholder tho

**Comment by Jakllp** [comment]
Updated https://wiki.mypet-plugin.de/hooks/placeholder
