### ISSUE TITLE
A fatal bug about this plugin!

### ISSUE THREAD

**Issue by mangoOvO123** [MyPetORG/MyPet#1693]
When running this plugin with version 1.21,If a player is attacked and killed by a pet, it will cause everyone to be kicked out of the server
the plugin version is MyPet-3.12-SNAPSHOT-B1768
![QQ图片20241107213452](https://github.com/user-attachments/assets/6f193cf5-74cb-4d7f-be0e-1ed866c055c2)

**Comment by Jakllp** [comment]
Fixed in [3.12-SNAPSHOT-B1769](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1769)
