### ISSUE TITLE
1.21.3 support

### ISSUE THREAD

**Issue by makegodhere** [MyPetORG/MyPet#1695]
paper updated to 1.21.3 - need update too

**Comment by Jakllp** [comment]
Already working on it (see 61883ab)

**Comment by makegodhere** [comment]
> Already working on it (see [61883ab](https://github.com/MyPetORG/MyPet/commit/61883aba1918dde259cdb6840601d886a1a87db2))

I look forward to it 🎉

**Comment by Jakllp** [comment]
Basic Support added with [3.12-SNAPSHOT-B1775](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1775).

Support for the new Mob-Variants is still missing but will follow.
