### ISSUE TITLE
blaze getting falling damage

### ISSUE THREAD

**Issue by makegodhere** [MyPetORG/MyPet#1697]
get blaze spawn
set hole under blaze
blaze getting falling damage

[3.12-SNAPSHOT-B1775](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1775)
paper 1.21.3

**Comment by Jakllp** [comment]
Cannot reproduce, seems to be some other plugin interfering

**Comment by makegodhere** [comment]
only mypet plugin in plugins list - same result

**Comment by Jakllp** [comment]
Oh so you aren't even talking about pets here.  
Well that changes things  
I've retested, and think I kinda know the cause but don't know how to fix it yet.  
Thanks for the report

**Comment by Jakllp** [comment]
Fixed in [3.12-SNAPSHOT-B1776](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1776)
