### ISSUE TITLE
enchantmets not working

### ISSUE THREAD

**Issue by makegodhere** [MyPetORG/MyPet#1698]
sword with smite 5 and without it getting same damage

![2024-12-08_00 24 43](https://github.com/user-attachments/assets/c42565a3-b23d-4ff5-b292-4d1edee82cb6)

![2024-12-08_00 24 40](https://github.com/user-attachments/assets/4032d5f7-b558-464c-a829-b8b563b7b73c)

if remove mypet plugin all good

it also affects on def enchants, for example protection on chestplates

[3.12-SNAPSHOT-B1775](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1775)
paper 1.21.3

**Comment by Jakllp** [comment]
Cannot reproduce, seems to be some other plugin interfering

**Comment by makegodhere** [comment]
only mypet plugin in plugins list - same result

**Comment by Jakllp** [comment]
Same here - normal results.  
Clean paper#81 on my end - which build are you using?

**Comment by makegodhere** [comment]
> Same here - normal results. Clean paper#81 on my end - which build are you using?

so strange
damage problems apper only if mypet plugin installing
🤨

**Comment by Jakllp** [comment]
Fixed in [3.12-SNAPSHOT-B1776](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1776)
